/**
 * CODEX OPENS WITH THE RECORD AND REFUSES THE WRITE, in the real Codex with the plugin installed
 * from this repository: the opening is in the first request, the mnema server's tools are offered,
 * a patch under a rule that refuses is not applied and the model is handed the rule, and a pause
 * for a person is not something Codex gives — a hook's `ask` is let through.
 *
 * WHAT IS HELD HERE AND WHAT IS NOT. The product's half — what `mnema before-a-write --host codex`
 * answers, and what `mnema brief --hook` prints — is `a-rule-that-refuses-a-write.test.ts` and the
 * brief's own cases. What Codex does with them is Codex's, read here off the requests it sends a
 * stand-in for the model and off the file that was or was not written. Codex's own ceiling for a
 * hook's text (2,500 tokens of 4 UTF-8 bytes, over which it hands a preview with its middle cut)
 * is held at its boundary, and so is the product cutting a long record under it at a whole rule.
 * NOT HELD: that the model reads what arrived; and any write that is not `apply_patch` — a file a
 * shell command writes meets no hook.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  A_HOOK_THAT_ANSWERS,
  aCodexForEachCase,
  aPatchAdding,
  theMessagesOf,
  theResultOfTheCall,
  theToolSearchSays,
} from './support/the-codex.js';
import { A_HOOK_THAT_SAYS_EXACTLY } from './support/the-host.js';
import { decide, ruleAt, theChannelFactsOf } from './support/the-record-to-stand-on.js';

describe('codex opens with the record and refuses the write', () => {
  const start = aCodexForEachCase();

  it('opens with the decision in force, and offers the mnema server', async () => {
    const session = await start({
      project: (project) => {
        decide(project, 'Bill in UTC');
      },
    });
    const first = session.requests[0];
    if (first === undefined) throw new Error('Codex never asked the model');
    const opening = theMessagesOf(first).filter((text) =>
      text.includes('Generated by `mnema brief`'),
    );
    expect(opening).toHaveLength(1);
    expect(opening[0]).toContain('Bill in UTC');
    // The plugin's server came up: Codex lists it, with the instructions only its handshake gives.
    expect(theToolSearchSays(session)).toContain(
      '- mnema: mnema is this project’s record of the decisions behind the work',
    );
  }, 180_000);

  /** The one message of a request that carries the opening document. */
  const theOpening = (texts: readonly string[]) =>
    texts.filter((text) => text.includes('Generated by `mnema brief`'));

  for (const [bytes, whole] of [
    [10_000, true],
    [10_001, false],
  ] as const) {
    it(`a hook's text of ${bytes} bytes arrives ${whole ? 'whole' : 'as a preview with its middle cut'}`, async () => {
      // The boundary the opening is cut to (2,500 tokens of 4 bytes), measured on the host
      // with a hook of the person's own: what holds that the margin under it is zero.
      const session = await start({
        ownHooks: {
          SessionStart: [
            {
              hooks: [
                { type: 'command', command: `node "${A_HOOK_THAT_SAYS_EXACTLY}" ${bytes} plain` },
              ],
            },
          ],
        },
      });
      const first = session.requests[0];
      if (first === undefined) throw new Error('Codex never asked the model');
      const text = 'a'.repeat(bytes);
      const arrived = theMessagesOf(first).filter((one) => one.includes('aaaaaaaaaa'));
      expect(arrived).toHaveLength(1);
      expect(arrived[0]?.includes(text)).toBe(whole);
      expect(arrived[0]?.includes('truncated output')).toBe(!whole);
    }, 180_000);
  }

  it('a record too long for the ceiling opens with whole rules, cut by the product and not by Codex', async () => {
    const session = await start({
      project: (project) => {
        for (let n = 1; n <= 160; n += 1) {
          decide(project, `Use the shared ledger client for service number ${n}`);
        }
      },
    });
    const first = session.requests[0];
    if (first === undefined) throw new Error('Codex never asked the model');
    const opening = theOpening(theMessagesOf(first));
    expect(opening).toHaveLength(1);
    const text = opening[0] as string;
    // Codex handed over what the product printed, not a preview of it.
    expect(text).not.toContain('truncated output');
    expect(text).not.toContain('Full hook output saved to');
    expect(Math.ceil(Buffer.byteLength(text, 'utf8') / 4)).toBeLessThanOrEqual(2_500);
    // The product cut it, at a whole rule, and said so in Codex's unit.
    expect(text).toContain('Left out of this text:');
    expect(text).toContain('at most 2,500 tokens of 4 bytes');
    const rules = text.split('\n').filter((line) => line.startsWith('- **'));
    expect(rules.length).toBeGreaterThan(0);
    expect(rules.at(-1)).toMatch(/^- \*\*.+\*\* · `[0-9a-f-]{36}` · accepted by .+\)$/);
  }, 600_000);

  it('deny: the patch is not applied and the model reads the rule that refused it', async () => {
    let rule = '';
    const session = await start({
      project: (project) => {
        rule = ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
      },
      patch: aPatchAdding('src/frozen/invoice.ts'),
    });
    expect(existsSync(join(session.project, 'src/frozen/invoice.ts'))).toBe(false);
    const handed = theResultOfTheCall(session);
    expect(handed, 'Codex never handed the model a result').toBeDefined();
    expect(handed).toContain('refuses a write at src/frozen/invoice.ts');
    expect(handed).toContain(rule);
    expect(theChannelFactsOf(session.project, session.home)).toMatchObject({
      'channel.refused': 1,
      'channel.asked': 0,
    });
  }, 180_000);

  it('fails open: with no `mnema` on the PATH the gate says nothing, and the patch is applied', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
      },
      patch: aPatchAdding('src/frozen/invoice.ts'),
      mnemaOnPath: false,
    });
    // The hook ran and answered nothing; a gate that cannot say why it stops somebody does not.
    expect(session.stderr).toContain('hook: PreToolUse');
    expect(existsSync(join(session.project, 'src/frozen/invoice.ts'))).toBe(true);
    expect(theChannelFactsOf(session.project, session.home)['channel.refused']).toBe(0);
  }, 180_000);

  for (const plugin of ['mnema', 'mnema-server-only'] as const) {
    it(`${plugin}: Codex starts the server as \`mnema mcp\`, with nothing left unexpanded`, async () => {
      const session = await start({ plugin });
      const server = JSON.parse(session.server) as Record<string, unknown>;
      const transport = (server['transport'] ?? server) as Record<string, unknown>;
      expect(transport['command']).toBe('mnema');
      expect(transport['args']).toEqual(['mcp']);
      expect(session.server).not.toContain('${');
    }, 180_000);
  }

  it('control: a path a rule only governs is written, and the plugin said nothing to stop it', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Bill in UTC', 'src/billing', 'governs');
      },
      patch: aPatchAdding('src/billing/invoice.ts'),
    });
    expect(existsSync(join(session.project, 'src/billing/invoice.ts'))).toBe(true);
    expect(theChannelFactsOf(session.project, session.home)).toMatchObject({
      'channel.refused': 0,
      'channel.asked': 0,
    });
  }, 180_000);

  /** A hook of the person's own, beside the plugin's, that answers `decision` for every patch. */
  const aHookThatAnswers = (decision: 'ask' | 'deny') => ({
    PreToolUse: [
      {
        matcher: 'apply_patch',
        hooks: [{ type: 'command', command: `node "${A_HOOK_THAT_ANSWERS}" ${decision}` }],
      },
    ],
  });

  it('ask: Codex does not hold a write for a person — a hook that answers `ask` is let through', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Ledger changes need finance', 'src/ledger', 'asks-for-a-person');
      },
      patch: aPatchAdding('src/ledger/entry.ts'),
      ownHooks: aHookThatAnswers('ask'),
    });
    // The host counts that hook's answer as a failure of the hook, and the patch is applied.
    expect(session.stderr).toContain('hook: PreToolUse Failed');
    expect(existsSync(join(session.project, 'src/ledger/entry.ts'))).toBe(true);
    // And the plugin, which knows that, asked nobody and recorded no asking.
    expect(theChannelFactsOf(session.project, session.home)).toMatchObject({
      'channel.asked': 0,
      'channel.refused': 0,
    });
  }, 180_000);

  it('control for the case above: the same hook of its own, answering `deny`, stops the patch', async () => {
    const session = await start({
      patch: aPatchAdding('src/ledger/entry.ts'),
      ownHooks: aHookThatAnswers('deny'),
    });
    expect(session.stderr).toContain('hook: PreToolUse Blocked');
    expect(existsSync(join(session.project, 'src/ledger/entry.ts'))).toBe(false);
    expect(theResultOfTheCall(session)).toContain("a hook of the person's own answered deny");
  }, 180_000);
});
