/**
 * COPILOT CLI OPENS WITH THE RECORD, REFUSES THE WRITE AND ASKS A PERSON, in the real Copilot CLI
 * with the plugin installed from this repository: the opening is in the first request, the mnema
 * server is listed, a write under a rule that refuses is not made and the model is handed the
 * rule, and a write under a rule that asks for a person is held — denied where no person is
 * there (`copilot -p`), put to the person where one is.
 *
 * WHAT IS HELD HERE AND WHAT IS NOT. The product's half — what `mnema before-a-write --host
 * copilot` answers, and what `mnema brief --hook` prints — is `a-rule-that-refuses-a-write.test.ts`
 * and the brief's own cases. What Copilot does with them is Copilot's, read here off the requests
 * it sends a stand-in for the model and off the file that was or was not written.
 * NOT HELD: that the model reads what arrived; the ceiling of a hook's text and the 15 seconds a
 * hook has (read in the documentation, not measured); and any file a shell command writes.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  aCopilotForEachCase,
  creating,
  NO,
  patching,
  theResultOfTheCall,
  theUserBlocksOf,
  YES,
} from './support/the-copilot.js';
import { decide, ruleAt, theChannelFactsOf } from './support/the-record-to-stand-on.js';

describe('copilot cli opens with the record, refuses the write and asks a person', () => {
  const start = aCopilotForEachCase();

  it('opens with the decision in force, and lists the mnema server', async () => {
    const session = await start({
      project: (project) => {
        decide(project, 'Bill in UTC');
      },
    });
    const first = session.requests[0];
    if (first === undefined) throw new Error('Copilot never asked the model');
    const opening = theUserBlocksOf(first).filter((text) =>
      text.includes('Generated by `mnema brief`'),
    );
    expect(opening).toHaveLength(1);
    expect(opening[0]).toContain('Bill in UTC');
    expect(session.server).toContain('mnema');
  }, 180_000);

  it('deny: the file is not created and the model reads the rule that refused it', async () => {
    let rule = '';
    const session = await start({
      project: (project) => {
        rule = ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
      },
      call: creating('src/frozen/invoice.ts'),
    });
    expect(existsSync(join(session.project, 'src/frozen/invoice.ts'))).toBe(false);
    const handed = theResultOfTheCall(session);
    expect(handed, 'Copilot never handed the model a result').toBeDefined();
    expect(handed).toContain('refuses a write at src/frozen/invoice.ts');
    expect(handed).toContain(rule);
    expect(theChannelFactsOf(session.project, session.home)).toMatchObject({
      'channel.refused': 1,
      'channel.asked': 0,
    });
  }, 180_000);

  it('deny, for a model whose write tool is `apply_patch`: the patch is not applied', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
      },
      model: 'gpt-5.1-codex',
      call: patching('src/frozen/invoice.ts'),
    });
    expect(existsSync(join(session.project, 'src/frozen/invoice.ts'))).toBe(false);
    expect(theResultOfTheCall(session)).toContain('refuses a write at src/frozen/invoice.ts');
    expect(theChannelFactsOf(session.project, session.home)['channel.refused']).toBe(1);
  }, 180_000);

  it('fails open: with no `mnema` on the PATH the gate says nothing, and the file is created', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
      },
      call: creating('src/frozen/invoice.ts'),
      mnemaOnPath: false,
    });
    expect(existsSync(join(session.project, 'src/frozen/invoice.ts'))).toBe(true);
    expect(theChannelFactsOf(session.project, session.home)['channel.refused']).toBe(0);
  }, 180_000);

  for (const plugin of ['mnema', 'mnema-server-only'] as const) {
    it(`${plugin}: Copilot lists the server as \`mnema mcp\`, with nothing left unexpanded`, async () => {
      const session = await start({ plugin });
      expect(session.server).toContain('"mnema"');
      expect(session.server).toContain('mcp');
      expect(session.server).not.toContain('${');
    }, 180_000);
  }

  it('control: a path a rule only governs is created, and the plugin said nothing to stop it', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Bill in UTC', 'src/billing', 'governs');
      },
      call: creating('src/billing/invoice.ts'),
    });
    expect(existsSync(join(session.project, 'src/billing/invoice.ts'))).toBe(true);
    expect(theChannelFactsOf(session.project, session.home)).toMatchObject({
      'channel.refused': 0,
      'channel.asked': 0,
    });
  }, 180_000);

  it('ask, with no person (`copilot -p`): the host counts it a denial, and the file is not created', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Ledger changes need finance', 'src/ledger', 'asks-for-a-person');
      },
      call: creating('src/ledger/entry.ts'),
    });
    expect(existsSync(join(session.project, 'src/ledger/entry.ts'))).toBe(false);
    expect(theChannelFactsOf(session.project, session.home)['channel.asked']).toBe(1);
  }, 180_000);

  for (const [keys, written] of [
    [YES, true],
    [NO, false],
  ] as const) {
    it(`ask, with a person who ${written ? 'agrees' : 'declines'}: the file is ${written ? '' : 'not '}created`, async () => {
      const session = await start({
        project: (project) => {
          ruleAt(project, 'Ledger changes need finance', 'src/ledger', 'asks-for-a-person');
        },
        call: creating('src/ledger/entry.ts'),
        person: keys,
      });
      expect(session.screen).toContain('Do you want to allow');
      // Only an answer closes the prompt: once it is closed the host draws its input line again
      // below it, and a person who pressed nothing leaves the prompt as the last thing on screen.
      const afterThePrompt = session.screen.slice(session.screen.lastIndexOf('esc to cancel'));
      // (The screen is read as latin1, so the heavy right-pointing angle quotation mark U+276F
      // arrives as its three UTF-8 bytes.)
      expect(afterThePrompt.includes('\u00e2\u009d\u00af'), 'the prompt was never answered').toBe(
        true,
      );
      expect(existsSync(join(session.project, 'src/ledger/entry.ts'))).toBe(written);
      expect(theChannelFactsOf(session.project, session.home)['channel.asked']).toBe(1);
    }, 240_000);
  }
});
