/**
 * GEMINI CLI OPENS WITH THE RECORD AND REFUSES THE WRITE, in the real Gemini CLI with the
 * extension of this tree installed: the opening is in the first turn of the conversation, the
 * server's tools are offered, a write under a rule that refuses is not made and the model is handed
 * the rule — for `write_file` and for `replace` — and a rule that only asks for a person is let
 * through, because the extension pauses nothing.
 *
 * WHAT IS HELD HERE AND WHAT IS NOT. The product's half — what `mnema before-a-write --host
 * gemini` answers, and what `mnema brief --hook` prints — is `a-rule-that-refuses-a-write.test.ts`
 * and the brief's own cases. What Gemini CLI does with them is the host's, read here off the
 * requests it sends a stand-in for the model and off the file that was or was not written.
 * NOT HELD: that the model reads what arrived; a ceiling Gemini CLI may put on the opening; the
 * script's behaviour when `mnema` outlasts its 15 seconds; an interactive session, where the host
 * documents the opening as the first turn of the history; and any file a shell command writes.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  aGeminiForEachCase,
  replacing,
  theResultOfTheCall,
  theToolsOf,
  theUserTextsOf,
  writing,
} from './support/the-gemini.js';
import { aFile, decide, ruleAt, theChannelFactsOf } from './support/the-record-to-stand-on.js';

describe('gemini cli opens with the record and refuses the write', () => {
  const start = aGeminiForEachCase();

  it('opens with the decision in force, in the first turn, and offers the mnema server', async () => {
    const session = await start({
      project: (project) => {
        decide(project, 'Bill in UTC');
      },
    });
    const withTools = session.requests.filter((request) => theToolsOf(request).length > 0);
    const first = withTools[0];
    if (first === undefined) throw new Error('Gemini CLI never offered the model a tool');
    // The host escapes the angle brackets of a hook's text and wraps it in `<hook_context>`.
    const opening = theUserTextsOf(first).filter((text) =>
      text.includes('Generated by `mnema brief`'),
    );
    expect(opening).toHaveLength(1);
    expect(opening[0]).toContain('<hook_context>');
    expect(opening[0]).toContain('Bill in UTC');
    expect(theToolsOf(first)).toContain('mcp_mnema_record_decision');
  }, 180_000);

  it('asks the verbs for the opening once for the session, however many requests it makes', async () => {
    const session = await start({
      project: (project) => {
        decide(project, 'Bill in UTC');
      },
      call: writing('src/billing/invoice.ts'),
    });
    expect(session.requests.length).toBeGreaterThanOrEqual(2);
    expect(session.calls.filter((call) => call === 'brief --hook')).toHaveLength(1);
    expect(session.calls.filter((call) => call === 'recall --hook')).toHaveLength(1);
  }, 180_000);

  it('deny, `write_file`: the file is not created and the model reads the rule that refused it', async () => {
    let rule = '';
    const session = await start({
      project: (project) => {
        rule = ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
      },
      call: writing('src/frozen/invoice.ts'),
    });
    expect(existsSync(join(session.project, 'src/frozen/invoice.ts'))).toBe(false);
    const handed = theResultOfTheCall(session);
    expect(handed, 'Gemini CLI never handed the model a result').toBeDefined();
    expect(handed).toContain('refuses a write at src/frozen/invoice.ts');
    expect(handed).toContain(rule);
    expect(theChannelFactsOf(session.project, session.home)).toMatchObject({
      'channel.refused': 1,
      'channel.asked': 0,
    });
  }, 180_000);

  it('deny, `replace`: the file keeps what it had', async () => {
    let file = '';
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
        file = aFile(project, 'src/frozen/invoice.ts', 'export const total = 1;\n');
      },
      call: replacing('src/frozen/invoice.ts', 'total = 1', 'total = 2'),
    });
    expect(readFileSync(file, 'utf-8')).toBe('export const total = 1;\n');
    expect(theResultOfTheCall(session)).toContain('refuses a write at src/frozen/invoice.ts');
    expect(theChannelFactsOf(session.project, session.home)['channel.refused']).toBe(1);
  }, 180_000);

  it('fails open: with no `mnema` on the PATH the script says nothing, and the file is created', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
      },
      call: writing('src/frozen/invoice.ts'),
      mnema: 'absent',
    });
    expect(existsSync(join(session.project, 'src/frozen/invoice.ts'))).toBe(true);
    expect(theChannelFactsOf(session.project, session.home)['channel.refused']).toBe(0);
  }, 180_000);

  it('runs no verb of a program named mnema that is not this product, and the file is created', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
      },
      call: writing('src/frozen/invoice.ts'),
      mnema: 'a stranger',
    });
    expect(existsSync(join(session.project, 'src/frozen/invoice.ts'))).toBe(true);
    expect(session.calls).toContain('--identify');
    expect(session.calls.filter((call) => /^(brief|recall|before-a-write)/.test(call))).toEqual([]);
    for (const request of session.requests) {
      expect(theUserTextsOf(request).join('\n')).not.toContain('not the record');
    }
  }, 180_000);

  it('with no extension installed, the same write is created: it is the extension that refuses', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Billing is frozen', 'src/frozen', 'refuses-a-write');
      },
      call: writing('src/frozen/invoice.ts'),
      extension: false,
    });
    expect(existsSync(join(session.project, 'src/frozen/invoice.ts'))).toBe(true);
    expect(theChannelFactsOf(session.project, session.home)['channel.refused']).toBe(0);
  }, 180_000);

  it('control: a path a rule only governs is created, and the extension said nothing to stop it', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Bill in UTC', 'src/billing', 'governs');
      },
      call: writing('src/billing/invoice.ts'),
    });
    expect(existsSync(join(session.project, 'src/billing/invoice.ts'))).toBe(true);
    expect(theChannelFactsOf(session.project, session.home)).toMatchObject({
      'channel.refused': 0,
      'channel.asked': 0,
    });
  }, 180_000);

  it('ask: a rule that only asks for a person is let through, and no asking is recorded', async () => {
    const session = await start({
      project: (project) => {
        ruleAt(project, 'Ledger changes need finance', 'src/ledger', 'asks-for-a-person');
      },
      call: writing('src/ledger/entry.ts'),
    });
    expect(existsSync(join(session.project, 'src/ledger/entry.ts'))).toBe(true);
    expect(theChannelFactsOf(session.project, session.home)).toMatchObject({
      'channel.refused': 0,
      'channel.asked': 0,
    });
  }, 180_000);
});
