import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';

import matter from 'gray-matter';
import { z } from 'zod';

import type { Skill } from '../domain/entities/skill.js';
import { ActorKind } from '../domain/enums/actor-kind.js';
import { ErrorCode } from '../errors/error-codes.js';
import type { MnemaError } from '../errors/mnema-error.js';
import type { SkillRepository } from '../storage/sqlite/repositories/skill-repository.js';
import { writeFileAtomic } from '../utils/atomic-write.js';
import type { AuditService } from './audit-service.js';
import type { IdentityService } from './identity-service.js';
import { Err, Ok, type Result } from './result.js';

/**
 * Severity of a skill-lint diagnostic.
 *
 * - `error`: blocks publication of the skill (missing required field,
 *   referenced tool unknown, malformed frontmatter)
 * - `warning`: skill is usable but the catalogue convention is not
 *   met (e.g. missing example section, version not semver)
 */
export type SkillSeverity = 'error' | 'warning';

/**
 * One diagnostic emitted by {@link SkillService.lint}.
 */
export interface SkillDiagnostic {
  readonly file: string;
  readonly severity: SkillSeverity;
  readonly message: string;
}

/**
 * Outcome of a full lint pass.
 */
export interface SkillLintReport {
  readonly diagnostics: readonly SkillDiagnostic[];
  readonly filesScanned: number;
  readonly errorCount: number;
  readonly warningCount: number;
}

/**
 * Validated metadata extracted from a skill's YAML frontmatter.
 *
 * Names match the design vocabulary: `name` is the catalogue key,
 * `version` follows semver, `tools_used` lists the MCP tools the skill
 * leans on so the lint can flag stale references.
 */
export const SkillFrontmatterSchema = z.object({
  name: z.string().min(1),
  version: z.string().regex(/^\d+\.\d+\.\d+(-[\w.]+)?$/),
  description: z.string().min(1),
  tools_used: z.array(z.string()).default([]),
});

export type SkillFrontmatter = z.infer<typeof SkillFrontmatterSchema>;

/**
 * Mode controlling whether `record` overwrites the latest version
 * (`update`) or creates a new version row (`new_version`).
 */
export type SkillRecordMode = 'update' | 'new_version';

/**
 * Input for {@link SkillService.record}.
 */
export interface SkillRecordInput {
  readonly slug: string;
  readonly name: string;
  readonly description: string;
  readonly content: string;
  readonly toolsUsed?: readonly string[];
  readonly mode?: SkillRecordMode;
  readonly actor: string;
  readonly via?: string;
  readonly runId?: string;
}

/**
 * Outcome of {@link SkillService.record}: the resulting skill row plus
 * a hint of what happened (created v1, bumped to vN, overwrote in place,
 * or no-op because content was already identical).
 */
export interface SkillRecordResult {
  readonly skill: Skill;
  readonly action: 'created' | 'updated' | 'new_version' | 'no_op';
}

/**
 * Skill catalogue: lint (filesystem-only, read-only) and record/show/use
 * (SQLite-backed, agent-facing).
 *
 * Filesystem mirror: when a skill is recorded, the service writes
 * `<skillsDir>/<slug>.md` atomically so humans can see the same content.
 * Frontmatter is generated by the service — agents pass semantic fields,
 * not raw YAML.
 */
export class SkillService {
  /**
   * Filename used as the skill catalogue index. Excluded from lint.
   */
  static readonly INDEX_FILE = 'SKILL.md';

  constructor(
    private readonly skillsDir: string,
    private readonly knownTools: ReadonlySet<string>,
    private readonly repo: SkillRepository | null = null,
    private readonly identity: IdentityService | null = null,
    private readonly audit: AuditService | null = null,
  ) {}

  private requireRecordDeps(): {
    readonly repo: SkillRepository;
    readonly identity: IdentityService;
    readonly audit: AuditService;
  } {
    if (this.repo === null || this.identity === null || this.audit === null) {
      throw new Error(
        'SkillService was constructed in lint-only mode; record/show/use require the full DI tuple',
      );
    }
    return { repo: this.repo, identity: this.identity, audit: this.audit };
  }

  /**
   * Walks `skillsDir` and returns one diagnostic per problem found.
   *
   * Files that are neither `.md` nor `.markdown` are ignored.
   *
   * @returns Aggregate report with severity counts
   */
  lint(): SkillLintReport {
    if (!existsSync(this.skillsDir)) {
      return { diagnostics: [], filesScanned: 0, errorCount: 0, warningCount: 0 };
    }

    const diagnostics: SkillDiagnostic[] = [];
    const files = readdirSync(this.skillsDir, { withFileTypes: true })
      .filter((entry) => entry.isFile())
      .map((entry) => entry.name)
      .filter((name) => name.endsWith('.md') || name.endsWith('.markdown'))
      .filter((name) => name !== SkillService.INDEX_FILE);

    for (const filename of files) {
      const filePath = path.join(this.skillsDir, filename);
      diagnostics.push(...this.lintFile(filePath));
    }

    const errorCount = diagnostics.filter((d) => d.severity === 'error').length;
    const warningCount = diagnostics.filter((d) => d.severity === 'warning').length;
    return { diagnostics, filesScanned: files.length, errorCount, warningCount };
  }

  /**
   * Records a skill. Three paths:
   *
   * - slug unknown → creates v1, regardless of `mode`.
   * - slug known and `mode='update'` (default): if content is byte-equal
   *   to the latest version, no-op. Otherwise overwrites the latest row
   *   in place.
   * - slug known and `mode='new_version'`: inserts a new row with
   *   version = latest + 1 (even if content matches; the agent asked).
   *
   * @param input - Skill fields + identity tuple
   * @returns Outcome describing the action taken
   */
  record(input: SkillRecordInput): SkillRecordResult {
    const { repo, identity, audit } = this.requireRecordDeps();
    const createdBy = identity.ensureActor(input.actor, ActorKind.Human);
    const toolsUsed = input.toolsUsed ?? [];
    const latest = repo.findLatestBySlug(input.slug);
    const mode: SkillRecordMode = input.mode ?? 'update';

    let action: SkillRecordResult['action'];
    let resulting: Skill;

    if (latest === null) {
      resulting = repo.insert({
        slug: input.slug,
        name: input.name,
        version: 1,
        description: input.description,
        content: input.content,
        toolsUsed,
        createdBy,
      });
      action = 'created';
    } else if (mode === 'new_version') {
      resulting = repo.insert({
        slug: input.slug,
        name: input.name,
        version: latest.version + 1,
        description: input.description,
        content: input.content,
        toolsUsed,
        createdBy,
      });
      action = 'new_version';
    } else {
      const sameContent =
        latest.content === input.content &&
        latest.name === input.name &&
        latest.description === input.description &&
        toolsArraysEqual(latest.toolsUsed, toolsUsed);
      if (sameContent) {
        resulting = latest;
        action = 'no_op';
      } else {
        const updated = repo.updateContent(latest.id, {
          name: input.name,
          description: input.description,
          content: input.content,
          toolsUsed,
        });
        if (updated === null) {
          throw new Error('skill update returned null after a known row');
        }
        resulting = updated;
        action = 'updated';
      }
    }

    if (action !== 'no_op') {
      this.writeMirror(resulting);
    } else if (!this.mirrorExists(resulting)) {
      // F-8: a no_op record (content byte-equal to the stored row) does
      // not normally rewrite the mirror — but if the mirror file went
      // missing in the meantime, regenerate it so SQLite and the file
      // tree stay in sync without forcing a content change.
      this.writeMirror(resulting);
    }

    audit.write({
      kind: 'skill_recorded',
      actor: input.actor,
      via: input.via,
      run: input.runId,
      data: {
        slug: resulting.slug,
        version: resulting.version,
        action,
      },
    });

    return { skill: resulting, action };
  }

  /**
   * Returns a skill by slug. If `version` is omitted, the latest version
   * is returned.
   *
   * @param slug - Skill slug
   * @param version - Optional specific version
   * @returns The skill or an error
   */
  show(slug: string, version?: number): Result<Skill, MnemaError> {
    const { repo } = this.requireRecordDeps();
    const skill =
      version !== undefined
        ? repo.findBySlugAndVersion(slug, version)
        : repo.findLatestBySlug(slug);
    if (skill === null) {
      return Err({ kind: ErrorCode.SkillNotFound, slug });
    }
    return Ok(skill);
  }

  /**
   * Lists the latest version of every recorded skill, ordered by
   * `usage_count` then recency.
   *
   * @returns Skill rows
   */
  list(): readonly Skill[] {
    const { repo } = this.requireRecordDeps();
    return repo.listLatest();
  }

  /**
   * Lists every version recorded under a slug, newest first.
   *
   * @param slug - Skill slug
   * @returns Skill rows
   */
  listVersions(slug: string): readonly Skill[] {
    const { repo } = this.requireRecordDeps();
    return repo.listBySlug(slug);
  }

  /**
   * Increments the usage counter on the latest version of a slug and
   * stamps `last_used_at`.
   *
   * @param slug - Skill slug
   * @param actor - Identity tuple for audit
   * @param via - Optional client annotation
   * @param runId - Optional run id
   * @returns The updated skill or an error
   */
  recordUse(slug: string, actor: string, via?: string, runId?: string): Result<Skill, MnemaError> {
    const { repo, audit } = this.requireRecordDeps();
    const updated = repo.incrementUsage(slug);
    if (updated === null) {
      return Err({ kind: ErrorCode.SkillNotFound, slug });
    }
    audit.write({
      kind: 'skill_used',
      actor,
      via,
      run: runId,
      data: { slug, version: updated.version, usage_count: updated.usageCount },
    });
    return Ok(updated);
  }

  /**
   * Regenerates missing `.md` mirror files for the latest version of
   * every recorded slug. Existing mirrors are left alone — this only
   * heals drift, not reformats human-edited content. Returns the slugs
   * whose mirror was just rewritten.
   *
   * @returns Slugs whose mirror file was created during this call
   */
  rebuildMirrors(): string[] {
    const { repo } = this.requireRecordDeps();
    const rebuilt: string[] = [];
    for (const skill of repo.listLatest()) {
      if (!this.mirrorExists(skill)) {
        this.writeMirror(skill);
        rebuilt.push(skill.slug);
      }
    }
    return rebuilt;
  }

  private mirrorExists(skill: Skill): boolean {
    return existsSync(path.join(this.skillsDir, `${skill.slug}.md`));
  }

  private writeMirror(skill: Skill): void {
    const filePath = path.join(this.skillsDir, `${skill.slug}.md`);
    const frontmatter = [
      '---',
      `name: ${quoteYaml(skill.name)}`,
      `version: ${skill.version}.0.0`,
      `description: ${quoteYaml(skill.description)}`,
      `tools_used: ${JSON.stringify(skill.toolsUsed)}`,
      `usage_count: ${skill.usageCount}`,
      skill.lastUsedAt !== null ? `last_used_at: ${skill.lastUsedAt}` : null,
      '---',
      '',
    ]
      .filter((line) => line !== null)
      .join('\n');
    writeFileAtomic(filePath, `${frontmatter + skill.content}\n`);
  }

  private lintFile(filePath: string): SkillDiagnostic[] {
    const out: SkillDiagnostic[] = [];
    let raw: string;
    try {
      raw = readFileSync(filePath, 'utf-8');
    } catch (error) {
      const message = error instanceof Error ? error.message : 'unknown read error';
      return [{ file: filePath, severity: 'error', message: `cannot read: ${message}` }];
    }

    let parsed: matter.GrayMatterFile<string>;
    try {
      parsed = matter(raw);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'unknown parse error';
      return [{ file: filePath, severity: 'error', message: `malformed frontmatter: ${message}` }];
    }

    const validation = SkillFrontmatterSchema.safeParse(parsed.data);
    if (!validation.success) {
      for (const issue of validation.error.issues) {
        const where = issue.path.length > 0 ? issue.path.map(String).join('.') : '<root>';
        out.push({
          file: filePath,
          severity: 'error',
          message: `frontmatter.${where}: ${issue.message}`,
        });
      }
      return out;
    }
    const front = validation.data;

    for (const tool of front.tools_used) {
      if (!this.knownTools.has(tool)) {
        out.push({
          file: filePath,
          severity: 'error',
          message: `references unknown MCP tool "${tool}"`,
        });
      }
    }

    if (!hasExample(parsed.content)) {
      out.push({
        file: filePath,
        severity: 'warning',
        message: 'no `## Example` section — skills should include at least one worked example',
      });
    }

    return out;
  }
}

function hasExample(body: string): boolean {
  return /^##\s+example\b/im.test(body);
}

function toolsArraysEqual(a: readonly string[], b: readonly string[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

function quoteYaml(value: string): string {
  if (/[:#&*!|>{}[\],?\-'"`%@\\\n]/.test(value)) {
    return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }
  return value;
}

/**
 * Hashes a string deterministically for content-equality checks across
 * record calls. Currently unused outside tests but exported so suites can
 * reuse the exact comparison logic when needed.
 *
 * @param content - String to hash
 * @returns Hex SHA-256 digest
 */
export function contentDigest(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}
