import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { parseFrontmatter } from '../../storage/markdown/frontmatter.js';
import { CURATED_MEMORY_SUBFOLDERS, listMirrorEntries } from '../../utils/mirror-layout.js';

/**
 * One entry rendered in a regenerated `INDEX.md`.
 *
 * Mirrors what an agent needs to decide whether to read the file in
 * full: a stable identifier, a short title, and any per-file metadata
 * (status / tags) the consolidator picked up from the frontmatter.
 */
export interface IndexEntry {
  readonly file: string;
  readonly title: string;
  readonly status: string | null;
  readonly tags: readonly string[];
}

/**
 * Per-folder summary returned by {@link MemoryConsolidator.run}.
 */
export interface ConsolidatedSection {
  readonly indexPath: string;
  readonly entries: readonly IndexEntry[];
}

/**
 * Aggregate summary of a consolidation run.
 */
export interface ConsolidationSummary {
  readonly memory: ConsolidatedSection | null;
  readonly decisions: ConsolidatedSection | null;
  readonly notes: ConsolidatedSection | null;
}

const MANAGED_HEADER = '<!-- MNEMA: managed section, regenerated by `mnema memory consolidate` -->';
const MANAGED_FOOTER = '<!-- /MNEMA -->';

/**
 * Regenerates the `INDEX.md` files that live alongside the human-curated
 * memory tree.
 *
 * DESIGN.md §11.7 separates audit ("what happened") from memory ("why
 * it happened, what we decided"). Memory is curated by humans; the
 * indices, however, are mechanical: they list every file present, with
 * the title and metadata pulled from the YAML frontmatter (when any).
 *
 * The consolidator writes only inside an `MNEMA: managed section`
 * block — anything the human added before or after that block is
 * preserved verbatim. Re-running the consolidator with no new files
 * yields a byte-identical output, so it is safe to put under CI or a
 * git pre-commit hook.
 *
 * Stratification, decision supersession, and notes-to-decisions
 * promotion are explicit non-goals of the alpha — they require human
 * judgment that the consolidator deliberately does not encode.
 */
export class MemoryConsolidator {
  constructor(private readonly memoryDir: string) {}

  /**
   * Walks the memory tree and rewrites every `INDEX.md` found in the
   * canonical sub-folders.
   *
   * @returns A summary listing the files indexed in each section. A
   *   section is `null` when the corresponding folder does not exist.
   */
  run(): ConsolidationSummary {
    if (!existsSync(this.memoryDir)) {
      return { memory: null, decisions: null, notes: null };
    }
    return {
      memory: this.consolidateMemoryRoot(),
      decisions: this.consolidateSubfolder('decisions'),
      notes: this.consolidateSubfolder('notes'),
    };
  }

  /**
   * The top-level `memory/INDEX.md`. Since MNEMA-ADR-51 a scoped memory-row
   * mirror lives under `memory/<scope>/<slug>.md`, so the root index walks one
   * level of scope subfolders (via {@link listMirrorEntries}) in addition to
   * the scopeless files at the root — otherwise scoped memories silently drop
   * out of the index (and thus out of `context_bootstrap`). The curated
   * `decisions/` and `notes/` subfolders are their OWN sections and are
   * excluded here so they are not double-listed.
   */
  private consolidateMemoryRoot(): ConsolidatedSection {
    const entries = listMirrorEntries(this.memoryDir)
      .filter((e) => {
        const top = path.relative(this.memoryDir, e.filePath).split(path.sep)[0];
        return top === undefined || !CURATED_MEMORY_SUBFOLDERS.has(top);
      })
      .map((e) => {
        // Link target relative to memory/INDEX.md, POSIX-style for markdown.
        const rel = path.relative(this.memoryDir, e.filePath).split(path.sep).join('/');
        return extractEntry(e.filePath, rel);
      })
      .sort((a, b) => a.file.localeCompare(b.file));

    const indexPath = path.join(this.memoryDir, 'INDEX.md');
    writeIndex(indexPath, 'Memory index', entries);
    return { indexPath, entries };
  }

  private consolidateSubfolder(name: string): ConsolidatedSection | null {
    const dir = path.join(this.memoryDir, name);
    if (!existsSync(dir)) return null;
    return this.consolidateFolder(dir, ['INDEX.md']);
  }

  private consolidateFolder(dir: string, exclude: readonly string[]): ConsolidatedSection {
    const entries: IndexEntry[] = [];
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile()) continue;
      if (!entry.name.endsWith('.md')) continue;
      if (exclude.includes(entry.name)) continue;
      entries.push(extractEntry(path.join(dir, entry.name)));
    }
    entries.sort((a, b) => a.file.localeCompare(b.file));

    const indexPath = path.join(dir, 'INDEX.md');
    writeIndex(indexPath, dirNameForHeading(dir, this.memoryDir), entries);

    return { indexPath, entries };
  }
}

function dirNameForHeading(dir: string, memoryRoot: string): string {
  const relative = path.relative(memoryRoot, dir);
  if (relative === '' || relative === '.') return 'Memory index';
  // Capitalise: `decisions` → `Decisions index`.
  const head = relative.charAt(0).toUpperCase() + relative.slice(1);
  return `${head} index`;
}

/**
 * Writes the regenerated `INDEX.md` while preserving anything the
 * human authored outside the `MNEMA` managed block.
 */
function writeIndex(indexPath: string, heading: string, entries: readonly IndexEntry[]): void {
  const managed = renderManagedBlock(entries);
  const previous = existsSync(indexPath) ? readFileSync(indexPath, 'utf-8') : '';
  const next = mergePreservingFreeSections(previous, heading, managed);
  writeFileSync(indexPath, next, 'utf-8');
}

function renderManagedBlock(entries: readonly IndexEntry[]): string {
  const lines: string[] = [];
  lines.push(MANAGED_HEADER);
  if (entries.length === 0) {
    lines.push('');
    lines.push('_(no files yet)_');
    lines.push('');
  } else {
    lines.push('');
    for (const entry of entries) {
      const meta: string[] = [];
      if (entry.status !== null) meta.push(`status: ${entry.status}`);
      if (entry.tags.length > 0) meta.push(`tags: ${entry.tags.join(', ')}`);
      const suffix = meta.length > 0 ? `  _(${meta.join(' · ')})_` : '';
      lines.push(`- [${entry.title}](${entry.file})${suffix}`);
    }
    lines.push('');
  }
  lines.push(MANAGED_FOOTER);
  return lines.join('\n');
}

function mergePreservingFreeSections(previous: string, heading: string, managed: string): string {
  if (previous.length === 0) {
    return `# ${heading}\n\n${managed}\n`;
  }
  const headerStart = previous.indexOf(MANAGED_HEADER);
  const footerStart = previous.indexOf(MANAGED_FOOTER, headerStart + MANAGED_HEADER.length);
  if (headerStart !== -1 && footerStart !== -1) {
    const before = previous.slice(0, headerStart);
    const after = previous.slice(footerStart + MANAGED_FOOTER.length);
    return `${before}${managed}${after}`;
  }
  // First time we touch a hand-written index: append the managed block
  // at the end so anything the human wrote keeps its place.
  const trimmed = previous.endsWith('\n') ? previous : `${previous}\n`;
  return `${trimmed}\n${managed}\n`;
}

// `displayPath` is the link target written into the INDEX (relative to the
// index's own directory). It defaults to the basename for a flat file; the
// memory root passes a scope-relative path (e.g. `scope-x/foo.md`) so a scoped
// mirror's link resolves from `memory/INDEX.md`.
function extractEntry(filePath: string, displayPath?: string): IndexEntry {
  const file = displayPath ?? path.basename(filePath);
  const raw = readFileSync(filePath, 'utf-8');
  let parsed: ReturnType<typeof parseFrontmatter>;
  try {
    parsed = parseFrontmatter(raw);
  } catch {
    return {
      file,
      title: stripExtension(path.basename(filePath)),
      status: null,
      tags: [],
    };
  }

  const data = parsed.data as Record<string, unknown>;
  const titleFromFrontmatter = typeof data.title === 'string' ? data.title : null;
  const titleFromHeading = firstHeading(parsed.content);
  const title = titleFromFrontmatter ?? titleFromHeading ?? stripExtension(path.basename(filePath));

  const status = typeof data.status === 'string' ? data.status : null;
  const tags = Array.isArray(data.tags)
    ? data.tags.filter((tag): tag is string => typeof tag === 'string')
    : [];

  return {
    file,
    title,
    status,
    tags,
  };
}

function firstHeading(body: string): string | null {
  const match = body.match(/^#\s+(.+)$/m);
  if (match === null) return null;
  return (match[1] ?? '').trim() || null;
}

function stripExtension(filename: string): string {
  const dot = filename.lastIndexOf('.');
  return dot === -1 ? filename : filename.slice(0, dot);
}
