import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import type { Config } from '../../../config/config-schema.js';
import type { Task } from '../../../domain/entities/task.js';
import type { Workflow } from '../../../domain/state-machine/state-machine.js';
import type { DependencyService } from '../../../services/dependency-service.js';
import type { IdentityService } from '../../../services/identity-service.js';
import type { InboxService } from '../../../services/inbox-service.js';
import type { LabelService } from '../../../services/label-service.js';
import type { MemoryService } from '../../../services/memory-service.js';
import type { MemoryStalenessService } from '../../../services/memory-staleness.js';
import type { ObservationService } from '../../../services/observation-service.js';
import type { SearchService } from '../../../services/search-service.js';
import type { SkillService } from '../../../services/skill-service.js';
import type { TaskService } from '../../../services/task-service.js';
import { ok } from '../../mcp-tool-result.js';
import { describeToolSurface } from '../../tool-registry.js';

/**
 * Registers the `context_bootstrap` MCP tool — the canonical entry
 * point every agent session should call before anything else.
 *
 * Returns project identity, the active workflow with a flattened
 * action summary, the contents of `AGENTS.md`, a `protocol` directive,
 * the current set of blockers, aggregate statistics, and three memory
 * surfaces. The `protocol` field restates — on every session start, so
 * it does not depend on the agent reading `AGENTS.md` — that durable
 * project knowledge goes through Mnema, not the client's native memory.
 *
 * ## Memory hierarchy (source of truth = SQLite)
 *
 * - `memories_inventory` (SQLite, agent-authoritative): the canonical
 *   list of agent-recorded memories. This is the only surface the
 *   agent should write to (`memory_record`); reads should prefer this.
 * - `recent_observations` (SQLite, agent-authoritative): append-only
 *   ephemeral context the agent has captured.
 * - `memory_index` / `decisions_index` (file-based, human-authored):
 *   optional supplements regenerated by `mnema memory consolidate`.
 *   `null` when the index file doesn't exist. The agent **must not**
 *   write to these — they're a human-curation surface that mirrors
 *   what `mnema memory consolidate` produces from on-disk markdown.
 *
 * Decisions, sprints and epics will be added as their respective
 * services are implemented in later phases — for now those fields are
 * either omitted or stubbed.
 */
export class ContextBootstrapTool {
  constructor(
    private readonly config: Config,
    private readonly workflow: Workflow,
    private readonly projectRoot: string,
    private readonly taskService: TaskService,
    private readonly skillService: SkillService,
    private readonly memoryService: MemoryService,
    private readonly observationService: ObservationService,
    private readonly memoryStaleness: MemoryStalenessService,
    private readonly inboxService: InboxService,
    private readonly identityService: IdentityService,
    private readonly dependencyService: DependencyService,
    private readonly searchService: SearchService,
    private readonly labelService: LabelService,
  ) {}

  /**
   * Attaches the tool to a high-level {@link McpServer}.
   *
   * @param server - MCP server instance to register against
   */
  register(server: McpServer): void {
    server.registerTool(
      'context_bootstrap',
      {
        description:
          "Bootstrap the agent's understanding of this project. Call this once at the start of every session, BEFORE any other tool. Returns project identity, active workflow, recent decisions, and pointers to memory.",
      },
      () => this.handle(),
    );
  }

  /** Builds the bootstrap payload. */
  private handle(): ReturnType<typeof ok> {
    const all = this.taskService.list();
    const byState: Record<string, number> = {};
    for (const state of this.workflow.states) {
      byState[state] = 0;
    }
    for (const task of all) {
      byState[task.state] = (byState[task.state] ?? 0) + 1;
    }

    // `blocked` is only meaningful when the workflow declares the
    // `blockedState` feature. Workflows without it (e.g. `lean`)
    // legitimately have no notion of blocked, so we report 0 there
    // rather than counting an unrelated state.
    const blockedStateName = this.workflow.features.blockedState ? 'BLOCKED' : null;
    const blockers =
      blockedStateName === null ? [] : all.filter((t) => t.state === blockedStateName);

    // `in_progress` aims at "actively being worked on". Default/kanban/
    // jira-classic call it IN_PROGRESS; lean calls it DOING. We pick
    // the first match from a small alias list so the count is right
    // across the shipping workflows without forcing every workflow to
    // adopt the same literal.
    const inProgressAliases = ['IN_PROGRESS', 'DOING'];
    const inProgressStateName =
      inProgressAliases.find((alias) => this.workflow.states.includes(alias)) ?? null;
    const inProgressCount = inProgressStateName === null ? 0 : (byState[inProgressStateName] ?? 0);

    // Aging: tasks parked in a non-terminal state past the configured
    // threshold. This is the IN_REVIEW (and BLOCKED/IN_PROGRESS) limbo
    // where a transition waits on a human who never acts — surfaced here
    // so the rot is visible on every session start, not discovered by a
    // manual disk sweep. Age is measured from `updatedAt` (the last
    // transition), so a task resets its clock each time it actually moves.
    const terminalStates = new Set(this.workflow.terminal);
    const staleAfterDays = this.config.aging.stale_after_days;
    const nowMs = Date.now();
    const agedTasks = all
      .filter((t) => !terminalStates.has(t.state))
      .map((t) => ({
        key: t.key,
        state: t.state,
        title: t.title,
        updated_at: t.updatedAt,
        age_days: Math.floor((nowMs - new Date(t.updatedAt).getTime()) / 86_400_000),
      }))
      .filter((t) => t.age_days >= staleAfterDays)
      .sort((a, b) => b.age_days - a.age_days);

    const skills = this.skillService.list().slice(0, 20);
    const memories = this.memoryService.list().slice(0, 30);
    const recentObservations = this.observationService.list({ limit: 5 });

    // Build a tasks id→key map so observations can expose the
    // human-readable `related_task_key` instead of the internal UUID.
    const taskKeyById = new Map<string, string>();
    for (const task of all) taskKeyById.set(task.id, task.key);

    // The actor roster an agent can read to learn valid assignee handles
    // without running a CLI. `default` is the handle the session acts as —
    // and the one `me`/`self` resolve to on task_start/task_assign. Never
    // throws: an unconfigured identity reports a null default rather than
    // failing the whole bootstrap.
    const defaultActor = this.identityService.resolveDefaultActor().actor;
    const actors = {
      default: defaultActor,
      known: this.identityService.listActors(),
    };

    const nextAction = this.buildNextAction(
      all,
      inProgressStateName,
      defaultActor,
      blockers.length,
    );

    // Skills relevant to whatever the agent is about to work on, surfaced up
    // front so it does not have to go fetch them. Keyed on the focus task
    // (the in-progress one to resume, else the top ready one).
    const focusKey = nextAction.in_progress_task?.key ?? nextAction.top_ready_task?.key ?? null;
    const relevantSkills = focusKey === null ? [] : this.relevantSkillsFor(focusKey);

    return ok({
      project: {
        key: this.config.project.key,
        name: this.config.project.name,
        description: this.config.project.description ?? null,
      },
      // Who this session acts as, plus the roster of known actors. `me`
      // and `self` on task_start/task_assign resolve to `default`; any
      // handle under `known` is a valid assignee_id.
      actors,
      // What to do NOW, not just what exists. The rest of this payload is
      // Skills matching the focus task (labels + title/description), so the
      // relevant procedure arrives before the work starts, not as a list to
      // fetch. Compact: slug + one-line description; pull the body with
      // skill_show. Empty when nothing is in focus or nothing matches.
      relevant_skills: relevantSkills,
      // state; this is direction. Focus rule: resume work already in
      // progress before starting anything new; otherwise the top ready
      // task; otherwise unblock a blocker; otherwise the backlog is idle.
      next_action: nextAction,
      workflow: {
        name: this.workflow.name,
        description: this.workflow.description,
        states: this.workflow.states,
        initial: this.workflow.initial,
        terminal: this.workflow.terminal,
        available_actions_summary: this.summariseActions(),
      },
      // The MCP tool surface as a few conceptual layers, so the agent can
      // reason about ~4 buckets instead of a flat list. `enabled` reflects
      // this project's profile — a disabled layer's tools are listed but
      // are not registered (e.g. Knowledge is off in the audit-only profile).
      tool_groups: describeToolSurface(this.workflow, {
        epics: this.workflow.features.epics,
        sprints: this.workflow.features.sprints,
        knowledge: this.config.features.knowledge,
      }),
      agents_md: this.readTruncated('AGENTS.md', 8 * 1024),
      agents_md_path: existsSync(path.join(this.projectRoot, 'AGENTS.md')) ? 'AGENTS.md' : null,
      // Surfaced on every session start so the directive does not depend on
      // the agent having read AGENTS.md: durable project knowledge belongs in
      // Mnema (memory_record / skill_record / observation_record), not in the
      // client's own native memory, so it travels with the repo and is audited.
      protocol: {
        record_durable_knowledge_here:
          'Record durable facts, procedures and signals about this project with ' +
          'memory_record / skill_record / observation_record — not in your client’s ' +
          'native memory. Mnema mirrors them to versioned `.md` and the audit log; ' +
          'native memory stays local and leaves no trail.',
      },
      // Human-curated supplement: regenerated by `mnema memory
      // consolidate`. `null` when the file doesn't exist. Agents
      // must not write to this surface — use `memory_record` instead.
      memory_index: this.readTruncated(path.join(this.config.paths.memory, 'INDEX.md'), 4 * 1024),
      decisions_index: this.readTruncated(
        path.join(this.config.paths.memory, 'decisions', 'INDEX.md'),
        4 * 1024,
      ),
      open_blockers: blockers.map((task) => ({
        key: task.key,
        title: task.title,
        updated_at: task.updatedAt,
      })),
      statistics: {
        total: all.length,
        in_progress: inProgressCount,
        blocked: blockers.length,
        by_state: byState,
      },
      // Tasks stuck in a non-terminal state longer than
      // `aging.stale_after_days`, oldest first. Empty when nothing is
      // stale. `stale_after_days` echoes the active threshold so the
      // agent can explain why an item did (or did not) surface.
      // `sla_breaches` is the active cut: tasks past the per-state SLA
      // (the IN_REVIEW limbo and friends), what is actually overdue.
      aging: {
        stale_after_days: staleAfterDays,
        stale_tasks: agedTasks,
        sla_breaches: this.inboxService.slaBreaches(nowMs),
        wip_breaches: this.inboxService.wipBreaches(),
      },
      skills_inventory: skills.map((s) => ({
        slug: s.slug,
        name: s.name,
        version: s.version,
        description: s.description,
        usage_count: s.usageCount,
        last_used_at: s.lastUsedAt,
        // `user` skills come from ~/.config/mnema and are read-only
        // background knowledge; `project` skills live in this repo.
        source: s.source,
      })),
      memories_inventory: memories.map((m) => {
        // Advisory only: flag a memory whose cited file:line references
        // changed in git since it was written, so the agent knows which
        // memories to re-check against current code. Never blocks recall.
        const staleness = this.memoryStaleness.assess(m.content, m.updatedAt);
        return {
          slug: m.slug,
          title: m.title,
          topics: m.topics,
          source: m.source,
          stale: staleness.stale,
          // Contradicted memories stay listed but are marked so the agent
          // knows they are no longer the current truth (see the memory that
          // obsoleted them via provenance / memory_show).
          ...(m.obsoletedBy !== null ? { obsolete: true, obsoleted_by: m.obsoletedBy } : {}),
          ...(staleness.stale
            ? {
                stale_files: staleness.cited_files.filter((c) => c.changedSince).map((c) => c.path),
                // Turn the flag into an actionable nudge: re-record the
                // slug to refresh it, or archive it if it is obsolete.
                suggested_action:
                  `cited files changed since this was written — re-check against current code, ` +
                  `then \`memory_record\` to refresh it or \`memory_archive\` to retire it`,
              }
            : {}),
        };
      }),
      recent_observations: recentObservations.map((o) => ({
        id: o.id,
        content: o.content,
        topics: o.topics,
        related_task_key:
          o.relatedTaskId === null ? null : (taskKeyById.get(o.relatedTaskId) ?? null),
        at: o.at,
      })),
    });
  }

  /**
   * Turns the aggregate state into a single recommended next step.
   *
   * The rest of the bootstrap payload answers "what exists"; this answers
   * "what do I do now" — the thing an agent actually needs and today has
   * to infer for itself. The rule, in order:
   *
   * 1. **Resume in-progress work.** If the session's actor already has a
   *    task in progress, finishing it beats starting anything new; a fresh
   *    READY pick would fragment the work. Falls back to any in-progress
   *    task when none is assigned to this actor (still better to converge
   *    than to open a new front).
   * 2. **Start the top ready task.** Otherwise point at the highest-priority
   *    task whose blockers are all terminal — computed by DependencyService
   *    so a task blocked by an open dependency is never recommended.
   * 3. **Unblock.** Otherwise, if something is blocked, that is the lever.
   * 4. **Idle.** Otherwise the actionable backlog is empty.
   *
   * `recommended` is a human-readable one-liner; the structured fields let
   * a caller act without parsing it.
   */
  private buildNextAction(
    all: readonly Task[],
    inProgressStateName: string | null,
    defaultActor: string | null,
    blockerCount: number,
  ): {
    focus: 'resume' | 'start' | 'unblock' | 'idle';
    recommended: string;
    ready_count: number;
    top_ready_task: { key: string; title: string } | null;
    in_progress_task: { key: string; title: string } | null;
    blocker_count: number;
  } {
    // Ready tasks, honouring dependency gates. On the (unexpected) error
    // path we degrade to an empty list rather than failing the bootstrap —
    // direction is a convenience, never a reason to break session start.
    const readyResult = this.dependencyService.ready();
    const readyTasks = readyResult.ok ? readyResult.value : [];
    const topReady = [...readyTasks].sort(
      (a, b) => a.priority - b.priority || a.key.localeCompare(b.key),
    )[0];
    const topReadyTask =
      topReady === undefined ? null : { key: topReady.key, title: topReady.title };

    // In-progress work for this actor first, then anyone's. `defaultActor`
    // is a handle; tasks store an actor id, so resolve before comparing.
    const inProgress =
      inProgressStateName === null ? [] : all.filter((t) => t.state === inProgressStateName);
    const myActorId =
      defaultActor === null ? null : this.identityService.findActorIdByHandle(defaultActor);
    const mine = inProgress.filter((t) => t.assigneeId !== null && t.assigneeId === myActorId);
    const activeTask = mine[0] ?? inProgress[0];

    const base = {
      ready_count: readyTasks.length,
      top_ready_task: topReadyTask,
      blocker_count: blockerCount,
    };

    if (activeTask !== undefined) {
      return {
        focus: 'resume',
        recommended: `Resume ${activeTask.key} (${activeTask.title}) — it is in progress. Finish it before starting new work.`,
        in_progress_task: { key: activeTask.key, title: activeTask.title },
        ...base,
      };
    }
    if (topReadyTask !== null) {
      return {
        focus: 'start',
        recommended: `Start ${topReadyTask.key} (${topReadyTask.title}) — highest-priority ready task. task_start it before editing.`,
        in_progress_task: null,
        ...base,
      };
    }
    if (blockerCount > 0) {
      return {
        focus: 'unblock',
        recommended: `Nothing is ready to pick up, but ${String(blockerCount)} task(s) are blocked — resolve a blocker to unblock the queue.`,
        in_progress_task: null,
        ...base,
      };
    }
    return {
      focus: 'idle',
      recommended:
        'No ready or in-progress tasks and no blockers — the actionable backlog is empty. Plan work (task_create) or submit a DRAFT.',
      in_progress_task: null,
      ...base,
    };
  }

  /**
   * Skills whose text matches the focus task — its title, description and
   * labels — via the same FTS the `skill_suggest` tool uses, so the agent
   * gets the relevant procedure before it starts rather than a list to go
   * fetch. Compact (slug + one-liner); the body is pulled with skill_show.
   * Degrades to an empty list on any lookup/search error — this is a
   * convenience, never a reason to fail the bootstrap.
   */
  private relevantSkillsFor(
    taskKey: string,
  ): { slug: string; name: string | null; snippet: string }[] {
    const task = this.taskService.list().find((t) => t.key === taskKey);
    if (task === undefined) return [];
    const labels = this.labelService.listForTask(taskKey);
    const labelList = labels.ok ? labels.value : [];
    const labelWords = labelList.join(' ');

    const out: { slug: string; name: string | null; snippet: string }[] = [];
    const seen = new Set<string>();

    // Scope-matched skills lead: a skill whose `scope` equals one of the
    // task's labels is a deliberate, precise area match — a stronger signal
    // than a fuzzy full-text hit, so it is surfaced first and unconditionally.
    if (labelList.length > 0) {
      const scopes = new Set(labelList);
      for (const skill of this.skillService.list()) {
        if (skill.scope !== null && scopes.has(skill.scope) && !seen.has(skill.slug)) {
          seen.add(skill.slug);
          out.push({ slug: skill.slug, name: skill.name, snippet: skill.description });
        }
      }
    }

    // Then full-text matches on the task's words + labels. Quote each token so
    // nothing is read as FTS5 syntax; OR them so any overlap surfaces a
    // candidate. Mirrors skill_suggest's tokenisation.
    const terms = `${task.title} ${task.description ?? ''} ${labelWords}`
      .toLowerCase()
      .split(/[^\p{L}\p{N}]+/u)
      .filter((t) => t.length >= 4)
      .map((t) => `"${t}"`);
    if (terms.length > 0) {
      const result = this.searchService.search(terms.join(' OR '), {
        entities: ['skill'],
        perEntityLimit: 3,
      });
      if (result.ok) {
        for (const hit of result.value) {
          const slug = hit.key ?? '';
          if (!seen.has(slug)) {
            seen.add(slug);
            out.push({ slug, name: hit.title, snippet: hit.snippet });
          }
        }
      }
    }
    return out;
  }

  /** Reads a file relative to project root, truncated to maxBytes. */
  private readTruncated(relativePath: string, maxBytes: number): string | null {
    const fullPath = path.join(this.projectRoot, relativePath);
    if (!existsSync(fullPath)) return null;
    const content = readFileSync(fullPath, 'utf-8');
    if (content.length <= maxBytes) return content;
    return `${content.slice(0, maxBytes)}\n\n[...truncated]`;
  }

  /** Builds a human-readable summary of available actions. */
  private summariseActions(): string {
    const lines: string[] = [];
    for (const [from, actions] of Object.entries(this.workflow.transitions)) {
      for (const [action, transition] of Object.entries(actions)) {
        lines.push(`${action}: ${from} → ${transition.to}`);
      }
    }
    return lines.join('\n');
  }
}
