import { cpSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  type ChainLayout,
  type ChainWriter,
  catalogUpcasters,
  openChainForWriting,
} from '@mnema/chain';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { adrCollisions, projectDecisions } from '../projections/decision.js';
import { orderedEvents } from '../projections/order.js';
import type { Clock } from './clock.js';
import {
  acceptDecision,
  type DecisionWriteContext,
  recordDecision,
  rejectDecision,
  supersedeDecision,
} from './decision-operations.js';

const upcasters = catalogUpcasters();
const WHICH = 'claude';

let root: string;
let roots: string[] = [];

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'mnema-decision-'));
  roots = [root];
});

afterEach(() => {
  for (const r of roots) rmSync(r, { recursive: true, force: true });
});

/** A clock the test drives, so `at` is deterministic across appends. */
function fixedClock(): { clock: Clock; tick: () => void } {
  let n = 0;
  return {
    clock: () => `2026-07-21T00:00:${String(n).padStart(2, '0')}.000Z`,
    tick: () => {
      n += 1;
    },
  };
}

function contextFor(w: ChainWriter, r: string, clock: Clock): DecisionWriteContext {
  const layout: ChainLayout = { root: r };
  return { writer: w, layout, upcasters, clock };
}

/**
 * Records a decision and returns the minted id (and its frozen label). The id is
 * generated by the operation now, never chosen, so a test that later transitions
 * or supersedes the decision must carry back the id it was given.
 */
function mustRecord(
  ctx: DecisionWriteContext,
  input: { title: string; rationale: string; which?: string },
): { id: string; adr: string } {
  const result = recordDecision(ctx, input);
  if (!result.ok) throw new Error(`record failed: ${result.code}`);
  return { id: result.id, adr: result.adr };
}

/** Reads the decisions the chain currently proves. */
function decisionsOf(r: string) {
  return projectDecisions(orderedEvents({ root: r }, upcasters));
}

describe('recordDecision — the frozen ADR label', () => {
  it('assigns ADR-1 to the first decision and freezes it in the event', () => {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock } = fixedClock();
    const { id, adr } = mustRecord(contextFor(w, root, clock), {
      title: 'Use SQLite',
      rationale: 'Relational load.',
      which: WHICH,
    });
    expect(adr).toBe('ADR-1');
    // The label is part of the recorded fact, not derived on read.
    expect(decisionsOf(root).get(id)?.adr).toBe('ADR-1');
  });

  it('numbers decisions sequentially as they are recorded', () => {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock, tick } = fixedClock();
    const ctx = contextFor(w, root, clock);
    const adrs: string[] = [];
    for (let i = 0; i < 3; i += 1) {
      adrs.push(mustRecord(ctx, { title: `d${i}`, rationale: 'r' }).adr);
      tick();
    }
    expect(adrs).toEqual(['ADR-1', 'ADR-2', 'ADR-3']);
  });

  it('mints a distinct id for each record (no caller-chosen id to reuse)', () => {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock, tick } = fixedClock();
    const ctx = contextFor(w, root, clock);
    const first = mustRecord(ctx, { title: 'a', rationale: 'r' });
    tick();
    const second = mustRecord(ctx, { title: 'b', rationale: 'r' });
    // Two records are two decisions: the ids differ by construction, so the
    // old reused-id refusal has nothing to guard — there is no way to name an
    // existing id. Both are present, each with its own frozen label.
    expect(first.id).not.toBe(second.id);
    const d = decisionsOf(root);
    expect(d.get(first.id)?.adr).toBe('ADR-1');
    expect(d.get(second.id)?.adr).toBe('ADR-2');
    expect(d.get(first.id)?.title).toBe('a');
    expect(d.get(second.id)?.title).toBe('b');
  });

  it('records the writer anchor as who, distinct from the signing fingerprint', () => {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock } = fixedClock();
    mustRecord(contextFor(w, root, clock), { title: 't', rationale: 'r' });
    for (const e of orderedEvents({ root }, upcasters)) {
      expect(e.who).toBe(w.anchor);
      expect(e.signerFp).toBe(w.signerFingerprint);
    }
    expect(w.anchor.startsWith('mnid:')).toBe(true);
    expect(w.anchor).not.toBe(w.signerFingerprint);
  });

  it('refuses a decision where the agent IS the authorizing anchor', () => {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock } = fixedClock();
    const result = recordDecision(contextFor(w, root, clock), {
      title: 't',
      rationale: 'r',
      which: w.anchor,
    });
    expect(result).toMatchObject({ ok: false, code: 'WHO_IS_WHICH' });
  });
});

describe('the frozen number does not slip when a concurrent decision merges in', () => {
  // Two clones work offline. Clone A records d-aaa then
  // d-ccc and cites "ADR-2" (d-ccc). Clone B records d-bbb concurrently. After
  // the offline merge, a number DERIVED on read would renumber d-ccc to ADR-3
  // and make "ADR-2" point at d-bbb — the citation would lie. Because the
  // number is FROZEN at write time, d-ccc stays ADR-2 forever.
  it('a citation stays pointed at the decision it was written for', () => {
    const rootB = mkdtempSync(join(tmpdir(), 'mnema-decision-b-'));
    roots.push(rootB);

    // Clone A: two decisions, ADR-1 then ADR-2 (the cited one).
    const a = openChainForWriting(root, { keyRoot: root });
    const ca = fixedClock();
    const ctxA = contextFor(a, root, ca.clock);
    const first = mustRecord(ctxA, { title: 'a', rationale: 'r' });
    ca.tick();
    const cited = mustRecord(ctxA, { title: 'c', rationale: 'r' });
    expect(cited.adr).toBe('ADR-2'); // the human cites "ADR-2" = this decision

    // Clone B (its own tail/key): a concurrent decision, also ADR-1 locally.
    const b = openChainForWriting(rootB, { keyRoot: rootB });
    const cb = fixedClock();
    const concurrent = mustRecord(contextFor(b, rootB, cb.clock), { title: 'b', rationale: 'r' });

    // Offline merge: B's tail and key land in A's chain.
    cpSync(join(rootB, 'tails'), join(root, 'tails'), { recursive: true });
    cpSync(join(rootB, 'keys'), join(root, 'keys'), { recursive: true });

    // After the merge the cited decision is STILL ADR-2 — the citation did not
    // slip, even though B's concurrent decision also carries ADR-1.
    const merged = decisionsOf(root);
    expect(merged.get(cited.id)?.adr).toBe('ADR-2');
    expect(merged.get(first.id)?.adr).toBe('ADR-1');
    expect(merged.get(concurrent.id)?.adr).toBe('ADR-1'); // B's local number
  });

  it('surfaces the label collision the merge created (ADR-1 now held by two)', () => {
    const rootB = mkdtempSync(join(tmpdir(), 'mnema-decision-b-'));
    roots.push(rootB);
    const a = openChainForWriting(root, { keyRoot: root });
    const onA = mustRecord(contextFor(a, root, fixedClock().clock), { title: 'a', rationale: 'r' });
    const b = openChainForWriting(rootB, { keyRoot: rootB });
    const onB = mustRecord(contextFor(b, rootB, fixedClock().clock), {
      title: 'b',
      rationale: 'r',
    });
    cpSync(join(rootB, 'tails'), join(root, 'tails'), { recursive: true });
    cpSync(join(rootB, 'keys'), join(root, 'keys'), { recursive: true });

    // Both minted ADR-1 offline: the ids stay distinct (no merge), and the clash
    // is surfaced as a legibility note keyed by the label, ids sorted.
    const collisions = adrCollisions(decisionsOf(root).values());
    expect(collisions).toEqual([{ adr: 'ADR-1', ids: [onA.id, onB.id].sort() }]);
  });
});

describe('the decision transitions are gated against the chain', () => {
  it('accepts a proposed decision, requiring a note', () => {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock, tick } = fixedClock();
    const ctx = contextFor(w, root, clock);
    const { id } = mustRecord(ctx, { title: 't', rationale: 'r' });
    tick();
    const missing = acceptDecision(ctx, { id });
    expect(missing).toMatchObject({ ok: false, code: 'MISSING_PROOF' });
    const ok = acceptDecision(ctx, { id, fields: { note: 'agreed' } });
    expect(ok).toMatchObject({ ok: true, to: 'accepted' });
    expect(decisionsOf(root).get(id)?.state).toBe('accepted');
  });

  it('rejects a proposed decision', () => {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock, tick } = fixedClock();
    const ctx = contextFor(w, root, clock);
    const { id } = mustRecord(ctx, { title: 't', rationale: 'r' });
    tick();
    const ok = rejectDecision(ctx, { id, fields: { note: 'no' } });
    expect(ok).toMatchObject({ ok: true, to: 'rejected' });
  });

  it('refuses a transition on a decision that does not exist', () => {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock } = fixedClock();
    const result = acceptDecision(contextFor(w, root, clock), {
      id: 'd-ghost',
      fields: { note: 'n' },
    });
    expect(result).toMatchObject({ ok: false, code: 'UNKNOWN_DECISION' });
  });

  it('refuses an illegal move (accept an already-accepted decision)', () => {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock, tick } = fixedClock();
    const ctx = contextFor(w, root, clock);
    const { id } = mustRecord(ctx, { title: 't', rationale: 'r' });
    tick();
    acceptDecision(ctx, { id, fields: { note: 'ok' } });
    tick();
    const again = acceptDecision(ctx, { id, fields: { note: 'again' } });
    expect(again).toMatchObject({ ok: false, code: 'ILLEGAL_TRANSITION' });
  });
});

describe('supersede — the multi-entity move, with existence enforced', () => {
  /** Two recorded decisions; returns their minted ids (old, new) and the ctx. */
  function twoDecisions(): {
    ctx: DecisionWriteContext;
    tick: () => void;
    oldId: string;
    newId: string;
  } {
    const w = openChainForWriting(root, { keyRoot: root });
    const { clock, tick } = fixedClock();
    const ctx = contextFor(w, root, clock);
    const oldId = mustRecord(ctx, { title: 'old', rationale: 'r' }).id;
    tick();
    const newId = mustRecord(ctx, { title: 'new', rationale: 'r' }).id;
    tick();
    return { ctx, tick, oldId, newId };
  }

  it('supersedes an accepted decision and links both sides', () => {
    const { ctx, tick, oldId, newId } = twoDecisions();
    acceptDecision(ctx, { id: oldId, fields: { note: 'ok' } });
    tick();
    const ok = supersedeDecision(ctx, {
      id: oldId,
      by: newId,
      fields: { reason: 'replaced' },
    });
    expect(ok).toMatchObject({ ok: true, to: 'superseded' });
    const d = decisionsOf(root);
    expect(d.get(oldId)?.state).toBe('superseded');
    expect(d.get(oldId)?.supersededBy).toBe(newId);
    expect(d.get(newId)?.supersedes).toBe(oldId);
  });

  it('supersedes directly from proposed (no accept needed)', () => {
    const { ctx, oldId, newId } = twoDecisions();
    const ok = supersedeDecision(ctx, {
      id: oldId,
      by: newId,
      fields: { reason: 'r' },
    });
    expect(ok).toMatchObject({ ok: true, to: 'superseded' });
  });

  it('refuses a supersede whose successor does not exist (UNKNOWN_BY, anti-dangling)', () => {
    const { ctx, oldId } = twoDecisions();
    const result = supersedeDecision(ctx, {
      id: oldId,
      by: 'd-ghost',
      fields: { reason: 'r' },
    });
    expect(result).toMatchObject({ ok: false, code: 'UNKNOWN_BY' });
    // Nothing was written — the subject is still proposed.
    expect(decisionsOf(root).get(oldId)?.state).toBe('proposed');
  });

  it('refuses a self-supersede (SELF_SUPERSEDE from the gate)', () => {
    const { ctx, oldId } = twoDecisions();
    const result = supersedeDecision(ctx, {
      id: oldId,
      by: oldId,
      fields: { reason: 'r' },
    });
    expect(result).toMatchObject({ ok: false, code: 'SELF_SUPERSEDE' });
  });

  it('refuses a supersede whose subject does not exist (UNKNOWN_DECISION)', () => {
    const { ctx, newId } = twoDecisions();
    const result = supersedeDecision(ctx, {
      id: 'd-ghost',
      by: newId,
      fields: { reason: 'r' },
    });
    expect(result).toMatchObject({ ok: false, code: 'UNKNOWN_DECISION' });
  });

  it('refuses to supersede an already-superseded decision (terminal)', () => {
    const { ctx, tick, oldId, newId } = twoDecisions();
    // Record a third to be a second successor candidate.
    const newerId = mustRecord(ctx, { title: 'newer', rationale: 'r' }).id;
    tick();
    supersedeDecision(ctx, { id: oldId, by: newId, fields: { reason: 'r' } });
    tick();
    const again = supersedeDecision(ctx, {
      id: oldId,
      by: newerId,
      fields: { reason: 'r' },
    });
    expect(again).toMatchObject({ ok: false, code: 'ILLEGAL_TRANSITION' });
  });
});
