/**
 * THE TREE, RENDERED FOR BASH.
 *
 * Three lookup tables and one function. The tables are the tree (see `lookups.ts`):
 * what each level offers as a subcommand, what it accepts as a flag, and the values a
 * declaration enumerates. The function is the only logic there is — walk the words
 * already typed to find WHERE on the tree the line is, then answer with that level's
 * words.
 *
 * THE WALK IS IN THE SCRIPT because the shell is the only one that knows what has been
 * typed. It keeps a word only when the level reached so far declares it as a
 * subcommand, so a title (`mnema task "ship the parser"`) and a flag's value never
 * shift the level, and depth is not assumed: a third level added tomorrow is a row in
 * the tables and no change here.
 *
 * IT TARGETS BASH 3.2, which is the bash macOS still ships. So no `mapfile`, no
 * associative array, no `[[` where `[` does — the whole point is a file that loads
 * everywhere `bash` does, and a completion that fails to load fails SILENTLY.
 *
 * AND IT DOES NOT USE `compgen -W`, which is the idiom, for one reason: `-W` EXPANDS
 * every word of its list — brace, tilde, parameter, arithmetic and COMMAND substitution
 * — so a declaration that ever held `$(…)` would be executed by pressing Tab. Every word
 * here comes from a declaration and not from a caller, which is why this is a hazard and
 * not a hole; the filtering is a `case` over the words instead, which expands nothing,
 * and `the-shell-knows-the-verbs.test.ts` drives a real bash over a declaration holding
 * `$(…)` and asserts nothing ran.
 *
 * AND THE `=` IS BASH'S OWN ODDITY. `--color=` is three words to bash (`--color`, `=`,
 * the rest), because `=` is in `COMP_WORDBREAKS`, so the word before the cursor is the
 * `=` rather than the flag. Looking one further back where that happens is what makes
 * `mnema --color=<Tab>` answer the same three whens as `mnema --color <Tab>`.
 */

import { type CompletionRow, commandRows, flagRows, valueRows } from './lookups.js';
import { functionNameOf, posixQuoted } from './text.js';
import type { CompletionTree } from './tree.js';

/** The bash completion script for a command tree. */
export function bashScript(tree: CompletionTree): string {
  const fn = functionNameOf(tree.command);
  const command = tree.command;
  return [
    ...header(command),
    '',
    ...table(`${fn}_commands`, commandRows(tree)),
    '',
    ...table(`${fn}_flags`, flagRows(tree)),
    '',
    ...table(`${fn}_values`, valueRows(tree)),
    '',
    completer(fn),
    '',
    `complete -F ${fn} ${command}`,
  ].join('\n');
}

/** What the file says about itself, and how to load it. */
function header(command: string): readonly string[] {
  return [
    `# bash completion for ${command}, generated by \`${command} completion bash\`.`,
    '#',
    '# For this shell, now:',
    `#     source <(${command} completion bash)`,
    '# For every shell, once:',
    `#     ${command} completion bash > /etc/bash_completion.d/${command}`,
    '#',
    '# It completes verbs, subcommands, option names, and the values of an option whose',
    `# declaration enumerates them. It never runs ${command} to answer a Tab.`,
  ];
}

/** A table as a shell function over its first argument. */
function table(name: string, rows: readonly CompletionRow[]): readonly string[] {
  const lines = [`${name}() {`, '  case "$1" in'];
  for (const [key, words] of rows) {
    lines.push(`    ${posixQuoted(key)}) echo ${posixQuoted(words)} ;;`);
  }
  lines.push('    *) echo ;;', '  esac', '}');
  return lines;
}

/**
 * The completion function itself — the same shape whatever the tree holds.
 *
 * Written as one template rather than a list of lines so that the shell reads as shell
 * here. Every `${…}` a SHELL is meant to expand is escaped (`\${…}`); the two that are
 * not are the function's own name, which is the only thing about this text the tree
 * decides.
 */
function completer(fn: string): string {
  return `${fn}() {
  local cur='' prev='' path='' word='' offered='' i=1
  cur="\${COMP_WORDS[COMP_CWORD]}"
  if [ "$COMP_CWORD" -gt 0 ]; then
    prev="\${COMP_WORDS[$((COMP_CWORD - 1))]}"
  fi
  # \`--color=\` is three words to bash, so the flag is one further back.
  if [ "$prev" = "=" ] && [ "$COMP_CWORD" -gt 1 ]; then
    prev="\${COMP_WORDS[$((COMP_CWORD - 2))]}"
  fi
  # Where on the tree the line already is.
  while [ "$i" -lt "$COMP_CWORD" ]; do
    word="\${COMP_WORDS[$i]}"
    i=$((i + 1))
    case "$word" in
      -*) continue ;;
    esac
    case " $(${fn}_commands "$path") " in
      *" $word "*)
        if [ -z "$path" ]; then path="$word"; else path="$path $word"; fi
        ;;
    esac
  done
  # A flag whose values the declaration enumerates answers alone.
  offered="$(${fn}_values "$path:$prev")"
  if [ -z "$offered" ]; then
    offered="$(${fn}_commands "$path") $(${fn}_flags "$path") $(${fn}_values "$path:")"
  fi
  # Filtered here rather than by \`compgen -W\`, which would EXPAND every word.
  COMPREPLY=()
  for word in $offered; do
    case "$word" in
      "$cur"*) COMPREPLY[\${#COMPREPLY[@]}]="$word" ;;
    esac
  done
}`;
}
