/**
 * THE TREE, RENDERED FOR FISH — one declaration per candidate, which is fish's idiom.
 *
 * fish has no completion FUNCTION to write: a candidate is declared to the shell with
 * `complete`, guarded by a condition, and fish does the matching. So this rendering is
 * not the bash script with different plumbing — it is the same tree turned inside out,
 * one line per word instead of one table per level. Two small functions carry the only
 * thing fish cannot express as a condition: WHERE on the tree the line already is.
 *
 * IT USES FISH'S QUOTES, WHICH ARE NOT POSIX'S. Inside single quotes fish honours `\'`
 * and `\\` and nothing else, where bash and zsh honour nothing at all — so the escaping
 * lives in `fishQuoted` and every description goes through it. The five descriptions
 * this program declares with an apostrophe are what makes that not hypothetical.
 *
 * `string split` READS STDIN when it is given no string, which would hang a Tab, so the
 * level's words are PIPED into it rather than passed as an argument that might be
 * absent. A completion that hangs the terminal would be a worse defect than the one this
 * file exists to fix.
 *
 * `-f` ON EVERY LINE: this surface takes no filenames anywhere — an id is not a path —
 * so offering the current directory after `--note` would be noise in every menu. `-r`
 * says a flag takes a value and `-x` says it takes one of an enumerated set; both are
 * read off the declaration.
 *
 * `complete -c … -e` FIRST, so that sourcing the file twice in one session leaves one
 * set of candidates rather than two.
 */

import { fishQuoted, functionNameOf } from './text.js';
import type { CompletionFlag, CompletionNode, CompletionTree } from './tree.js';

/** The fish completion script for a command tree. */
export function fishScript(tree: CompletionTree): string {
  const fn = `_${functionNameOf(tree.command)}`;
  const command = tree.command;
  const lines = [
    ...header(command),
    '',
    ...commandsFunction(`${fn}_commands`, tree),
    '',
    ...pathFunction(fn),
    '',
    `complete -c ${command} -e`,
  ];
  for (const node of tree.nodes) lines.push('', ...candidatesOf(command, fn, node));
  return lines.join('\n');
}

/** What the file says about itself, and how to load it. */
function header(command: string): readonly string[] {
  return [
    `# fish completion for ${command}, generated by \`${command} completion fish\`.`,
    '#',
    '# For this shell, now:',
    `#     ${command} completion fish | source`,
    '# For every shell, once:',
    `#     ${command} completion fish > ~/.config/fish/completions/${command}.fish`,
    '#',
    '# It completes verbs, subcommands, option names, and the values of an option whose',
    `# declaration enumerates them, each with what its own help says. It never runs`,
    `# ${command} to answer a Tab.`,
  ];
}

/** The subcommands each level offers, as a `switch` over the path. */
function commandsFunction(name: string, tree: CompletionTree): readonly string[] {
  const offering = tree.nodes.filter((node) => node.commands.length > 0);
  if (offering.length === 0) return [`function ${name}`, '    echo', 'end'];
  const lines = [
    `function ${name} --description 'the subcommands one level of the tree offers'`,
    '    switch "$argv[1]"',
  ];
  for (const node of offering) {
    lines.push(
      `        case ${fishQuoted(node.path)}`,
      `            echo ${fishQuoted(node.commands.map((child) => child.word).join(' '))}`,
    );
  }
  lines.push('    end', 'end');
  return lines;
}

/** Where on the tree the typed line is, and the condition every candidate is guarded by. */
function pathFunction(fn: string): readonly string[] {
  return [
    `function ${fn}_path --description 'the subcommand path the line has reached'`,
    '    set -l path ""',
    '    set -l skipped 0',
    '    for word in (commandline -opc)',
    '        if test $skipped -eq 0',
    '            set skipped 1',
    '            continue',
    '        end',
    '        if string match -q -- \'-*\' "$word"',
    '            continue',
    '        end',
    `        set -l children (${fn}_commands "$path" | string split ' ')`,
    '        if contains -- "$word" $children',
    '            if test -z "$path"',
    '                set path "$word"',
    '            else',
    '                set path "$path $word"',
    '            end',
    '        end',
    '    end',
    '    echo "$path"',
    'end',
    '',
    `function ${fn}_at --description 'true when the line has reached this path'`,
    `    test (${fn}_path) = "$argv[1]"`,
    'end',
  ];
}

/** Every candidate one level offers, one `complete` per word. */
function candidatesOf(command: string, fn: string, node: CompletionNode): readonly string[] {
  const at = `complete -c ${command} -f -n ${fishQuoted(`${fn}_at "${node.path}"`)}`;
  const lines: string[] = [`# ${command}${node.path === '' ? '' : ` ${node.path}`}`];
  for (const child of node.commands) {
    const described = child.description === '' ? '' : ` -d ${fishQuoted(child.description)}`;
    lines.push(`${at} -a ${fishQuoted(child.word)}${described}`);
  }
  for (const flag of node.flags) {
    const spelled = [
      ...(flag.short === undefined ? [] : [`-s ${flag.short.replace(/^-/, '')}`]),
      ...(flag.long === undefined ? [] : [`-l ${flag.long.replace(/^--/, '')}`]),
    ];
    lines.push(`${at} ${spelled.join(' ')}${valueSpecOf(flag)}`);
  }
  if (node.values.length > 0) lines.push(`${at} -a ${fishQuoted(node.values.join(' '))}`);
  return lines;
}

/**
 * What fish is told about a flag's value: the enumerated set, or that there is one.
 *
 * `-x` is both halves at once (it takes a value, and only these) — which is why an
 * enumerated flag does not also carry `-r`.
 */
function valueSpecOf(flag: CompletionFlag): string {
  if (flag.choices.length > 0) return ` -x -a ${fishQuoted(flag.choices.join(' '))}`;
  return flag.takesValue ? ' -r' : '';
}
