/**
 * THE TREE, RENDERED FOR ZSH — the one rendering that can show what a verb DOES.
 *
 * The tables are the same tree as bash's (see `lookups.ts`) and the walk is the same
 * walk, because both shells answer a Tab by looking up the level the line has reached.
 * What zsh adds is `_describe`, which puts a description beside each candidate in the
 * menu — so this rendering carries the fourth thing the tree holds: the one-line
 * description each command already declares for `--help`.
 *
 * A COMMAND'S DESCRIPTION TRAVELS AND AN OPTION'S DOES NOT, and the difference is
 * length, measured: the longest command description in this program is 76 characters
 * (`exposure`) and every one of them is written to sit in a column of the help's command
 * list, while `--which`'s is 340 and commander wraps it over five lines. A completion
 * menu is one line per candidate; a paragraph in one would push the candidates a caller
 * is choosing between off the screen. The flag names are offered without them, which is
 * what every generated completion in the market does.
 *
 * SPLITTING IS EXPLICIT EVERYWHERE. A description holds spaces, so the described
 * candidates are split on NEWLINES (`${(f)…}`) and the flag lists on words
 * (`${=…}`) — and each is asked only after the string is known to be non-empty, so an
 * empty level never reaches `_describe` or `compadd` as a single empty candidate.
 *
 * `#compdef` AND `compdef` BOTH, because a caller may install this file either way: the
 * first line is what an autoloaded function in `fpath` needs and a comment when the file
 * is sourced; the last line is what a sourced file needs and harmless when it is
 * autoloaded.
 */

import { type CompletionRow, commandRows, flagRows, valueRows } from './lookups.js';
import { functionNameOf, posixQuoted } from './text.js';
import type { CompletionTree } from './tree.js';

/** The zsh completion script for a command tree. */
export function zshScript(tree: CompletionTree): string {
  const fn = functionNameOf(tree.command);
  const command = tree.command;
  return [
    `#compdef ${command}`,
    ...header(command, fn),
    '',
    ...table(`${fn}_commands`, commandRows(tree)),
    '',
    ...described(`${fn}_described`, tree),
    '',
    ...table(`${fn}_flags`, flagRows(tree)),
    '',
    ...table(`${fn}_values`, valueRows(tree)),
    '',
    completer(fn),
    '',
    `compdef ${fn} ${command}`,
  ].join('\n');
}

/** What the file says about itself, and how to load it. */
function header(command: string, fn: string): readonly string[] {
  return [
    `# zsh completion for ${command}, generated by \`${command} completion zsh\`.`,
    '#',
    '# For this shell, now:',
    `#     source <(${command} completion zsh)`,
    '# For every shell, once:',
    `#     ${command} completion zsh > "\${fpath[1]}/${fn}"`,
    '#',
    '# It completes verbs, subcommands, option names, and the values of an option whose',
    `# declaration enumerates them, each with what its own help says. It never runs`,
    `# ${command} to answer a Tab.`,
  ];
}

/** A table as a shell function over its first argument. */
function table(name: string, rows: readonly CompletionRow[]): readonly string[] {
  const lines = [`${name}() {`, '  case "$1" in'];
  for (const [key, words] of rows) {
    lines.push(`    ${posixQuoted(key)}) echo ${posixQuoted(words)} ;;`);
  }
  lines.push('  esac', '}');
  return lines;
}

/**
 * The subcommands of each level as `_describe`'s `word:description` items.
 *
 * One item per LINE of the script, continued — the root offers one per verb, and a single
 * line holding the whole surface would be a file nobody can read a diff of.
 * `_describe` splits an item at its FIRST colon, so a description that holds one (the
 * gate's "dry-run the gate: would a move be allowed…") arrives whole.
 */
function described(name: string, tree: CompletionTree): readonly string[] {
  const lines = [`${name}() {`, '  case "$1" in'];
  for (const node of tree.nodes) {
    if (node.commands.length === 0) continue;
    lines.push(`    ${posixQuoted(node.path)}) printf '%s\\n' \\`);
    for (const [index, child] of node.commands.entries()) {
      const item = posixQuoted(`${child.word}:${child.description}`);
      const last = index === node.commands.length - 1;
      lines.push(`      ${item}${last ? ' ;;' : ' \\'}`);
    }
  }
  lines.push('  esac', '}');
  return lines;
}

/**
 * The completion function itself — the same shape whatever the tree holds.
 *
 * Written as one template rather than a list of lines so that the shell reads as shell
 * here. Every `${…}` the SHELL is meant to expand is escaped (`\${…}`); the two that are
 * not are the function's own name, which is the only thing about this text the tree
 * decides.
 */
function completer(fn: string): string {
  return `${fn}() {
  local prev='' path='' word='' text='' i=2
  local -a described offered
  # Where on the tree the line already is.
  while [ "$i" -lt "$CURRENT" ]; do
    word="\${words[$i]}"
    i=$((i + 1))
    case "$word" in
      -*) continue ;;
    esac
    case " $(${fn}_commands "$path") " in
      *" $word "*)
        if [ -z "$path" ]; then path="$word"; else path="$path $word"; fi
        ;;
    esac
  done
  if [ "$CURRENT" -gt 1 ]; then
    prev="\${words[$((CURRENT - 1))]}"
  fi
  # A flag whose values the declaration enumerates answers alone.
  text="$(${fn}_values "$path:$prev")"
  if [ -n "$text" ]; then
    compadd -- \${=text}
    return
  fi
  text="$(${fn}_described "$path")"
  if [ -n "$text" ]; then
    described=( \${(f)text} )
    _describe -t commands 'command' described
  fi
  text="$(${fn}_flags "$path") $(${fn}_values "$path:")"
  offered=( \${=text} )
  if [ \${#offered} -gt 0 ]; then
    compadd -- $offered
  fi
}`;
}
