/**
 * An entity's id: how it is MINTED, and the canonical form of a REFERENCE to it.
 *
 * An id is the one identity of an entity — minted by the operation that creates
 * it, never chosen by the caller. Deriving it here, from randomness, is the same
 * move the anchor `who` makes: two clones offline can never mint the same id, so
 * two unrelated tasks can never merge into one when their chains are unioned. A
 * caller-chosen id reopens exactly that false-merge (two clones both name a task
 * `t-1`, and the projection folds two histories onto one subject). So the create
 * operations call {@link mintId}; only a REFERENCE to an already-minted id (a
 * transition's subject, a supersede's `by`) is ever supplied.
 *
 * An id is NOT an identity of a person. Unlike a `who`/`which`, when taken as a
 * reference it is:
 *   - NOT trimmed — the chain does not trim, so trimming here would produce a
 *     key that no stored subject matches (an id never carries meaningful
 *     whitespace anyway; treating it verbatim keeps the reference and the
 *     stored subject byte-aligned).
 *   - NFC-normalized, because the chain NFC-normalizes every string into the
 *     bytes it serializes, so a reference read back from disk is always NFC.
 *     Comparing or looking up a reference in any other composition would
 *     false-miss against the projection, which keys on the NFC-from-disk form.
 *   - refused when the chain cannot canonicalize it (a lone surrogate), so the
 *     gate never authorizes a move the writer would then throw on appending.
 *
 * {@link canonicalId} is the id counterpart of {@link canonicalIdentity}: same
 * agreement with the chain, without the identity-only whitespace policy.
 */

import { randomBytes } from 'node:crypto';
import { CanonicalizationError, canonicalStringify } from '@mnema/chain';

/**
 * Mints a fresh entity id: a UUID version 7, per RFC 9562. The high 48 bits are
 * the current Unix time in milliseconds, so ids sort by creation time; the rest
 * is cryptographic randomness (`crypto.randomBytes`), so two ids minted in the
 * same millisecond — even across offline clones — do not collide. The version
 * (`7`) and variant (`10`) bits are set in place.
 *
 * It is generated by hand rather than from `crypto.randomUUID`: that helper
 * emits a v4 on every Node this package supports (`>= 20`), and its `{version:
 * 7}` option is not honored there (it silently returns a v4), which would break
 * {@link deriveAlias}'s contract that an id is "a v7 UUID that begins with a
 * timestamp". A dependency for a fixed 16-byte layout would add surface for no
 * gain; the layout is small and fully specified, so it lives here in the core
 * (never the zero-dependency chain).
 *
 * The result is a canonical id by construction (lowercase hex and dashes, no
 * whitespace, ASCII), so it never needs {@link canonicalId} run over it.
 */
export function mintId(): string {
  const bytes = randomBytes(16);
  const ms = Date.now();
  // 48-bit big-endian millisecond timestamp in bytes 0..5.
  bytes[0] = Math.floor(ms / 2 ** 40) & 0xff;
  bytes[1] = Math.floor(ms / 2 ** 32) & 0xff;
  bytes[2] = Math.floor(ms / 2 ** 24) & 0xff;
  bytes[3] = Math.floor(ms / 2 ** 16) & 0xff;
  bytes[4] = Math.floor(ms / 2 ** 8) & 0xff;
  bytes[5] = ms & 0xff;
  // Version 7 in the high nibble of byte 6; variant 0b10 in the high bits of
  // byte 8. `!` is safe: a 16-byte buffer always has these indices.
  bytes[6] = ((bytes[6] as number) & 0x0f) | 0x70;
  bytes[8] = ((bytes[8] as number) & 0x3f) | 0x80;
  const hex = bytes.toString('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/**
 * The canonical form of an id reference (NFC, chain-representable), or undefined
 * when the value is none — not a string, empty, or a string the chain cannot
 * canonicalize deterministically.
 */
export function canonicalId(value: unknown): string | undefined {
  if (typeof value !== 'string' || value.length === 0) return undefined;
  const canonical = value.normalize('NFC');
  if (canonical.length === 0) return undefined;
  try {
    canonicalStringify(canonical);
  } catch (error) {
    if (error instanceof CanonicalizationError) return undefined;
    throw error;
  }
  return canonical;
}
