/**
 * `verify --against-github`, at its seam: the trees a verification reported, and a `fetch`
 * handed in. Nothing here goes to the network.
 *
 * The known vector is the anchor of every other case: an Ed25519 key generated by
 * `ssh-keygen -t ed25519` (its `.pub` line, verbatim), the same key as an `spki` PEM converted
 * by Python's `cryptography` (`load_ssh_public_key(...).public_bytes(PEM, SubjectPublicKeyInfo)`),
 * and its raw 32 bytes and fingerprint from that same conversion. Two tools that are not this
 * code agree on what the two spellings of one key are; the parser has to agree with both.
 */

import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  accountLinked,
  type ChainWriter,
  catalogUpcasters,
  openChainForWriting,
  publicKeyPath,
  taskCreated,
  verify,
} from '@mnema/chain';
import { ensureFounded, linkAccount } from '@mnema/core/write';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { TreeReport } from './verify.js';
import { compareWithGithub, ed25519KeysIn, type FetchKeys, rawEd25519Of } from './verify-github.js';

const VECTOR_LINE =
  'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFOdNXf4vcaeWJ+fVPshQYYIbeABayDwac1AGmOW5Icc vector@example';
const VECTOR_PEM =
  '-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAU501d/i9xp5Yn59U+yFBhght4AFrIPBpzUAaY5bkhxw=\n-----END PUBLIC KEY-----\n';
const VECTOR_RAW = '539d3577f8bdc69e589f9f54fb214186086de0016b20f069cd401a6396e4871c';
const VECTOR_FP = 'a1ccb7bb33a655a0308bb82d699705018ca190292aedc85cd6269c93d2714910';

/** A published RSA key — a line an account may carry that is no key this record signs with. */
const RSA_LINE =
  'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDLN9/Hb2vZ8Cw1mH6hYzX0XQ6h3x4b3W3K4zE7vH1sGqfQ== rsa@example';

describe('the two spellings of one key', () => {
  it('reads the raw key out of the line ssh-keygen wrote, and skips every other line', () => {
    const published = [RSA_LINE, VECTOR_LINE, 'ssh-ed25519 not-base64-of-anything', ''].join('\n');
    expect(ed25519KeysIn(published)).toEqual([VECTOR_RAW]);
  });

  it('reads the same raw key out of the PEM, and nothing when the file is not the key it is named after', () => {
    expect(rawEd25519Of(VECTOR_PEM, VECTOR_FP)).toBe(VECTOR_RAW);
    expect(rawEd25519Of(VECTOR_PEM, '0'.repeat(64))).toBeUndefined();
  });

  it('refuses a security-key line, which is another key held in a device', () => {
    // The same 32 bytes under the `sk-ssh-ed25519@openssh.com` type are not this key.
    expect(ed25519KeysIn(VECTOR_LINE.replace('ssh-ed25519', 'sk-ssh-ed25519@openssh.com'))).toEqual(
      [],
    );
  });
});

let scratch: string[] = [];
afterEach(() => {
  for (const dir of scratch) rmSync(dir, { recursive: true, force: true });
  scratch = [];
});

function tmp(prefix: string): string {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  scratch.push(dir);
  return dir;
}

/** A tree with one task in it, signed and checkpointed by a fresh machine key. */
function aRecord(): { root: string; writer: ChainWriter } {
  const root = tmp('mnema-github-tree-');
  const writer = openChainForWriting(root, { keyRoot: tmp('mnema-github-keys-') });
  const ctx = { writer, layout: { root }, upcasters: catalogUpcasters() };
  // Founded and linked by the operation the verb runs, so the shape is the product's.
  const linked = linkAccount(ctx, { account: 'octocat' });
  if (!linked.ok) throw new Error(linked.message);
  writer.append(
    taskCreated(
      {
        at: new Date().toISOString(),
        who: writer.anchor,
        signerFp: writer.signerFingerprint,
        subject: '019f81f8-e400-7003-8000-000000000003',
      },
      { title: 'a task' },
    ),
  );
  writer.checkpoint();
  return { root, writer };
}

/** The OpenSSH line GitHub would publish for the key that signs `root`. */
function publishedLineFor(root: string, fingerprint: string): string {
  const raw = rawEd25519Of(readFileSync(publicKeyPath({ root }, fingerprint), 'utf-8'));
  if (raw === undefined) throw new Error('setup: no committed key');
  const type = Buffer.from('ssh-ed25519');
  const u32 = (n: number) => {
    const b = Buffer.alloc(4);
    b.writeUInt32BE(n);
    return b;
  };
  const wire = Buffer.concat([u32(type.length), type, u32(32), Buffer.from(raw, 'hex')]);
  return `ssh-ed25519 ${wire.toString('base64')} someone@laptop`;
}

function treesOf(root: string): TreeReport[] {
  return [{ kind: 'verdict', scope: 'public', root, result: verify(root) }];
}

/** A github.com that answers every account with `body` and `status`. */
function github(body: string, status = 200): FetchKeys & ReturnType<typeof vi.fn> {
  return vi.fn(async () => ({ status, text: async () => body }));
}

describe('compareWithGithub', () => {
  it('covers an author whose every signing key the linked account publishes', async () => {
    const { root, writer } = aRecord();
    const fetch = github([RSA_LINE, publishedLineFor(root, writer.signerFingerprint)].join('\n'));
    const reading = await compareWithGithub(treesOf(root), { fetch });

    expect(fetch).toHaveBeenCalledTimes(1);
    expect(fetch.mock.calls[0]?.[0]).toBe('https://github.com/octocat.keys');
    expect(reading.authors).toEqual([
      {
        anchor: writer.anchor,
        keys: [writer.signerFingerprint],
        finding: {
          kind: 'compared',
          account: 'octocat',
          published: [writer.signerFingerprint],
          unpublished: [],
        },
      },
    ]);
  });

  it('names a signing key the account does not publish', async () => {
    const { root, writer } = aRecord();
    const reading = await compareWithGithub(treesOf(root), { fetch: github(VECTOR_LINE) });
    expect(reading.authors[0]?.finding).toEqual({
      kind: 'compared',
      account: 'octocat',
      published: [],
      unpublished: [writer.signerFingerprint],
    });
  });

  it('says an account with no Ed25519 key has nothing to compare with', async () => {
    const { root } = aRecord();
    const reading = await compareWithGithub(treesOf(root), { fetch: github(RSA_LINE) });
    expect(reading.authors[0]?.finding).toEqual({ kind: 'no-ed25519-key', account: 'octocat' });
  });

  it('says github.com has no such account when it answers 404', async () => {
    const { root } = aRecord();
    const reading = await compareWithGithub(treesOf(root), { fetch: github('Not Found', 404) });
    expect(reading.authors[0]?.finding).toEqual({ kind: 'no-such-account', account: 'octocat' });
  });

  it('says github.com could not be reached, and does not throw, when the network fails', async () => {
    const { root } = aRecord();
    const fetch: FetchKeys = async () => {
      throw new TypeError('fetch failed');
    };
    const reading = await compareWithGithub(treesOf(root), { fetch });
    expect(reading.authors[0]?.finding).toEqual({
      kind: 'unreachable',
      account: 'octocat',
      detail: 'fetch failed',
    });
  });

  it('gives up on a github.com that does not answer, after the timeout', async () => {
    const { root } = aRecord();
    // Answers only when aborted — the shape of a host that never responds.
    const fetch: FetchKeys = (_url, { signal }) =>
      new Promise((_resolve, reject) => {
        signal.addEventListener('abort', () => reject(signal.reason));
      });
    const reading = await compareWithGithub(treesOf(root), { fetch, timeoutMs: 20 });
    expect(reading.authors[0]?.finding.kind).toBe('unreachable');
  });

  it('says an author with no linked account is not covered, and asks nothing', async () => {
    const root = tmp('mnema-github-tree-');
    const writer = openChainForWriting(root, { keyRoot: tmp('mnema-github-keys-') });
    ensureFounded({ writer, layout: { root }, upcasters: catalogUpcasters() });
    writer.append(
      taskCreated(
        {
          at: new Date().toISOString(),
          who: writer.anchor,
          signerFp: writer.signerFingerprint,
          subject: '019f81f8-e400-7003-8000-000000000003',
        },
        { title: 'a task' },
      ),
    );
    writer.checkpoint();
    const fetch = github('');
    const reading = await compareWithGithub(treesOf(root), { fetch });
    expect(reading.authors.map((a) => a.finding)).toEqual([{ kind: 'no-account' }]);
    expect(fetch).not.toHaveBeenCalled();
  });

  it('ignores a link above the last checkpoint — the window a keyless party can append to', async () => {
    const { root, writer } = aRecord();
    // A later link to another account, appended and never checkpointed.
    writer.append(
      accountLinked(
        {
          at: new Date(Date.now() + 1000).toISOString(),
          who: writer.anchor,
          signerFp: writer.signerFingerprint,
          subject: writer.anchor,
        },
        { service: 'github', account: 'mallory' },
      ),
    );
    const fetch = github(publishedLineFor(root, writer.signerFingerprint));
    const reading = await compareWithGithub(treesOf(root), { fetch });
    expect(fetch.mock.calls.map((call) => call[0])).toEqual(['https://github.com/octocat.keys']);
    expect(reading.authors[0]?.finding).toMatchObject({ kind: 'compared', account: 'octocat' });
  });

  /** A founded record whose author signed one claim of their own making, checkpointed. */
  function aRecordWithClaim(subjectOf: (anchor: string) => string, account: string) {
    const root = tmp('mnema-github-tree-');
    const writer = openChainForWriting(root, { keyRoot: tmp('mnema-github-keys-') });
    ensureFounded({ writer, layout: { root }, upcasters: catalogUpcasters() });
    writer.append(
      accountLinked(
        {
          at: new Date().toISOString(),
          who: writer.anchor,
          signerFp: writer.signerFingerprint,
          subject: subjectOf(writer.anchor),
        },
        { service: 'github', account },
      ),
    );
    writer.checkpoint();
    return root;
  }

  it('ignores a covered claim whose subject is another identity: an identity names only its own account', async () => {
    const root = aRecordWithClaim(() => `mnid:${'9'.repeat(64)}`, 'octocat');
    const fetch = github('');
    const reading = await compareWithGithub(treesOf(root), { fetch });
    expect(reading.authors.map((a) => a.finding)).toEqual([{ kind: 'no-account' }]);
    expect(fetch).not.toHaveBeenCalled();
  });

  it('refuses a covered claim whose account is no GitHub name, and never asks for it', async () => {
    const root = aRecordWithClaim((anchor) => anchor, '../octocat');
    const fetch = github('');
    const reading = await compareWithGithub(treesOf(root), { fetch });
    expect(reading.authors.map((a) => a.finding)).toEqual([
      { kind: 'not-an-account', account: '../octocat' },
    ]);
    expect(fetch).not.toHaveBeenCalled();
  });

  it('leaves out a tree whose verdict is a break, and says so', async () => {
    const { root, writer } = aRecord();
    // Rewrite the committed key: the checkpoints no longer verify against it.
    writeFileSync(publicKeyPath({ root }, writer.signerFingerprint), VECTOR_PEM, 'utf-8');
    const fetch = github('');
    const reading = await compareWithGithub(treesOf(root), { fetch });
    expect(reading).toEqual({ authors: [], notCompared: ['public'] });
    expect(fetch).not.toHaveBeenCalled();
  });
});
