/**
 * FORM D — the document: a file for a reader that never asked for it.
 *
 * The other three forms are answers on a terminal, read by a person who typed a
 * verb. This one is a FILE, and its reader is a model: `mnema brief > AGENTS.md`
 * puts the record where an agent host reads it on its own — `AGENTS.md` is an open
 * convention several of them read natively, `CLAUDE.md` is read when a session
 * opens — so what governs the work arrives without anyone thinking to ask. That is
 * why it is markdown with headings and bullets instead of aligned columns: the
 * indentation and the two-space gaps of form A mean something to an eye scanning a
 * terminal and nothing at all to the reader this is written for.
 *
 * THE BYTES ARE THE CONTRACT, and that is a requirement here rather than a
 * quality. A generated file rots: the record moves on and the copy in the
 * repository does not, and a stale rule read as a live one is worse than no file.
 * The only thing that detects it is `mnema brief | diff - AGENTS.md`, so this
 * document must be a pure function of the record — the same record twice is the
 * same bytes twice. Nothing here reads a clock, a path, a run, an actor or an
 * environment, and every fixed word is a constant rather than something composed at
 * print time. The two orders come from the derivations, which order by CONTENT, so
 * reading the trees in a different order cannot reshuffle it either.
 *
 * ONE LINE PER RULE, and this is the sharpest case of that rule in the product. A
 * decision's title is text an actor wrote; one holding a newline would end its own
 * bullet and start a second one, and the second would read as a rule the project
 * never made — in the one file whose whole purpose is that an agent obeys what is
 * in it. Every field taken from the record goes through {@link oneLine} for that
 * reason, the ids and the `ADR-<n>` labels included: the product mints both, but a
 * record can be appended to by anything holding a key, and "every field on the
 * line" is where that rule already stands. The fixed prose is wrapped by HAND, at
 * constants; nothing here wraps a value, because a wrapper over actor text would be
 * a second way to break a line.
 *
 * THE SKELETON IS ALWAYS THE SAME, empty record or full. A heading that disappeared
 * when its list was empty would make the diff of a first decision look like a
 * rewrite of the file, and — the reason that matters more — an absent section says
 * nothing, while an empty one says that nobody has decided yet. Those are different
 * facts, and the reader of this file is exactly the reader who cannot tell them
 * apart unless it is spelled out (see {@link NO_DECISIONS}).
 *
 * NOTHING IS CUT BY SIZE, so nothing here reports a total: with the whole list
 * printed, a count is the list's own length, and it is printed in the heading for a
 * reader who wants to check that nothing was lost between the record and this file.
 *
 * WHAT IS LEFT OUT IS DECLARED, and that is the other half of the same doctrine. The
 * composition carries the tree that TRAVELS and no other, so a rule recorded privately
 * is absent from this file — and an absence a reader cannot see is exactly what "no
 * silent cut" forbids, whether the cause is a limit or a scope. So the document names
 * its scope before any of the content ({@link WHAT_TRAVELS}) and says that a heading's
 * number is what is printed under it. What it does NOT do is count what it left out:
 * a "3 private rules omitted" would put a fact about the private tree into the file
 * that gets committed, and would move with that tree — two things this document exists
 * not to do.
 */

import type { Brief } from '@mnema/copilot';
import { oneLine } from '../served-patterns.js';

/**
 * The marker that says what this file is, to a reader and to a `grep`.
 *
 * It is an HTML comment so it does not render, and it is FIRST so that a person
 * looking at the top of a file in a diff learns before anything else that editing
 * it is pointless. One marker, not a begin/end pair: a pair would advertise that
 * something here can splice a section into a file it did not write, and nothing
 * can — the recipe is a redirection, and the whole of this output is the file.
 */
const GENERATED =
  '<!-- Generated by `mnema brief` from this project’s mnema record. Do not edit by hand. -->';

/** The heading: what the file IS, in the words the record's own reads use. */
const TITLE = '# What governs the work here';

/**
 * What the content is, said before any of it — the same declaration the agent's
 * surface makes when it serves a pattern into a prompt, in the medium this one uses.
 *
 * A file read on every prompt is read as instruction, and these lines are the only
 * chance to say whose instruction: the project's own people and agents, recorded and
 * served back. mnema does not vet what a decision says, and a reader that assumed
 * otherwise would be crediting this product for a call somebody else made.
 */
const WHAT_THIS_IS = [
  'These are the calls and the patterns recorded for this project — text the people and',
  'agents working on it wrote and settled, not instructions from mnema. Follow them.',
];

/**
 * WHICH record: the committed one, said before any of the content and beside the
 * declaration of what the content is.
 *
 * It is here because the omission has to be visible. What this file carries is the
 * tree that travels, so a rule recorded privately — on one machine, or for one person
 * — is not in it, and a reader of a governance document assumes they are holding all
 * of it. Two sentences, both load-bearing: the first names the scope, the second says
 * that the number in a heading counts what is printed under it and not what the record
 * holds elsewhere. Neither says HOW MANY were left out, deliberately — that count is a
 * fact about the private tree, and this file is committed.
 *
 * "Committed" rather than "public" because it is the word the reader can act on: it
 * names what a clone gets. `public` is the product's own name for the tree, and a file
 * read by an agent that never saw a `--scope` flag has no use for it.
 */
const WHAT_TRAVELS = [
  'It carries what is COMMITTED to this project — the record a clone of the repository',
  'gets, and nothing kept privately on one machine or for one person. A rule recorded',
  'that way is not below, and each heading counts what is printed under it.',
];

/**
 * How to make this file again, and how to find out that it is stale.
 *
 * The check is a pipe and a `diff` rather than a flag of this verb: the record is
 * what mnema is authoritative about, and comparing it to a file the operator keeps
 * wherever they like is a job the shell already does exactly. It is stated here, in
 * the file itself, because the person who finds a stale `AGENTS.md` is not
 * necessarily the person who generated it.
 */
const HOW_TO_REGENERATE = [
  'Regenerate this file with `mnema brief > AGENTS.md`, and check it with',
  '`mnema brief | diff - AGENTS.md` — a difference is either a copy that fell behind the',
  'record or an edit made here by hand, and an edit here is lost on the next run.',
];

/** Where the argument behind a decision is, since this file carries only the rule. */
const WHERE_THE_RATIONALE_IS = [
  'Each was accepted, and none of them superseded. For the argument behind one, ask',
  '`read_record` for its id.',
];

/** Where the pattern itself is, since this file carries only its name. */
const WHERE_THE_PATTERN_IS = [
  'Adopted here, and expected to be worked by. For the pattern itself, ask `skills`',
  'for its id.',
];

/**
 * What an empty list of decisions says, and why it is not "there are no rules".
 *
 * The two readings are different facts and this file's reader has no way to tell
 * them apart: an agent told there is nothing governing here proceeds as if that were
 * settled, when what is true is that nobody has settled anything. It is the same
 * failure the opening read names as the worst one it can have — an empty answer that
 * reads like an answer — in the place where it would be read most often.
 */
const NO_DECISIONS = [
  'Nothing has been decided here yet — which is not the same as there being no rules.',
  'No decision has been recorded and accepted in this project, so the record has none',
  'to hand over.',
];

/** What an empty list of patterns says, on the same distinction. */
const NO_PATTERNS = [
  'No pattern has been adopted here yet — which is not the same as there being no way',
  'of working here. The record holds none to hand over.',
];

/**
 * The whole document, as lines — the committed governance the composition handed over,
 * ready to be redirected into the file an agent host reads. It prints what it is given
 * and counts what it prints; which trees that came from is settled before it (see
 * `brief` in @mnema/copilot).
 */
export function briefDocument(governance: Brief): string[] {
  return [
    GENERATED,
    '',
    TITLE,
    '',
    ...WHAT_THIS_IS,
    '',
    ...WHAT_TRAVELS,
    '',
    ...HOW_TO_REGENERATE,
    '',
    ...section(
      'Decisions in force',
      governance.decisions.length,
      governance.decisions.length === 0 ? NO_DECISIONS : WHERE_THE_RATIONALE_IS,
      governance.decisions.map((decision) =>
        rule(`${decision.adr} — ${decision.title}`, decision.id),
      ),
    ),
    '',
    ...section(
      'Patterns adopted',
      governance.skills.length,
      governance.skills.length === 0 ? NO_PATTERNS : WHERE_THE_PATTERN_IS,
      governance.skills.map((skill) => rule(skill.name, skill.id)),
    ),
  ];
}

/**
 * One section: the heading with how many are PRINTED under it, what to do about them,
 * then one line each.
 *
 * The number is `items.length` and it is taken from the caller for that reason — the
 * count and the bullets come from one list, so a heading that says three over four
 * bullets is not a state this can reach. It is not a total of the record: what the
 * composition left out because it does not travel is declared in words at the top
 * ({@link WHAT_TRAVELS}), never as a number here, since a number would be a fact about
 * the private tree inside a committed file.
 *
 * Written once for both, because the two sections are the same shape and a shape
 * written twice is a shape that drifts — a heading that counts in one and not in the
 * other, a blank line in one and not the other, and a diff that reads as a change to
 * the file's structure rather than to the record.
 */
function section(
  heading: string,
  printed: number,
  says: readonly string[],
  items: readonly string[],
): string[] {
  return [`## ${heading} (${printed})`, '', ...says, ...(items.length > 0 ? ['', ...items] : [])];
}

/**
 * One rule, as a bullet: what it says, then the id that asks the record for the
 * rest.
 *
 * The name is bold because it is what the reader acts on, and the id is in a code
 * span because it is what they type into the read that serves the rest.
 *
 * BOTH halves go through {@link oneLine}, and they go through it HERE — the one
 * place a bullet is built. A caller that had to remember to collapse each field
 * before composing it is a caller that will forget on the field added next, and the
 * failure is silent: the file simply grows a rule the project never made. The
 * composed name is collapsed as a whole, so a break in either the label or the title
 * is closed by the same call.
 */
function rule(name: string, id: string): string {
  return `- **${oneLine(name)}** · \`${oneLine(id)}\``;
}
