import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { MemoryConsolidator } from '@/services/knowledge/memory-consolidator.js';

describe('MemoryConsolidator', () => {
  let memoryDir: string;

  beforeEach(() => {
    memoryDir = mkdtempSync(path.join(tmpdir(), 'mnema-memory-cons-'));
    mkdirSync(path.join(memoryDir, 'decisions'), { recursive: true });
    mkdirSync(path.join(memoryDir, 'notes'), { recursive: true });
  });

  afterEach(() => {
    rmSync(memoryDir, { recursive: true, force: true });
  });

  it('returns empty sections when memory dir is missing', () => {
    rmSync(memoryDir, { recursive: true, force: true });
    const summary = new MemoryConsolidator(memoryDir).run();
    expect(summary).toEqual({ memory: null, decisions: null, notes: null });
  });

  it('writes a fresh INDEX.md listing every file in the folder', () => {
    writeFileSync(path.join(memoryDir, 'context.md'), '# Project context\n\nbody\n', 'utf-8');

    const summary = new MemoryConsolidator(memoryDir).run();
    expect(summary.memory?.entries.map((e) => e.title)).toEqual(['Project context']);

    const indexBody = readFileSync(path.join(memoryDir, 'INDEX.md'), 'utf-8');
    expect(indexBody).toContain('[Project context](context.md)');
    expect(indexBody).toContain('<!-- MNEMA: managed section');
  });

  it('ADR-51: indexes scoped memory mirrors from their scope folder, linking correctly', () => {
    // A scopeless mirror at the root and a scoped one under its folder.
    writeFileSync(path.join(memoryDir, 'global.md'), '# Global fact\n', 'utf-8');
    mkdirSync(path.join(memoryDir, 'packages-notifier'), { recursive: true });
    writeFileSync(
      path.join(memoryDir, 'packages-notifier', 'rate-limit.md'),
      '# Rate limit\n',
      'utf-8',
    );
    // Curated subfolders must NOT be swept into the root index.
    writeFileSync(path.join(memoryDir, 'decisions', 'some-adr.md'), '# ADR\n', 'utf-8');

    const summary = new MemoryConsolidator(memoryDir).run();
    const titles = summary.memory?.entries.map((e) => e.title).sort();
    expect(titles).toEqual(['Global fact', 'Rate limit']); // scoped memory included, ADR excluded

    const indexBody = readFileSync(path.join(memoryDir, 'INDEX.md'), 'utf-8');
    // The scoped memory links through its folder so the path resolves.
    expect(indexBody).toContain('[Rate limit](packages-notifier/rate-limit.md)');
    expect(indexBody).toContain('[Global fact](global.md)');
    // The ADR is not double-listed in the root index (it has its own section).
    expect(indexBody).not.toContain('some-adr.md');
  });

  it('preserves human-authored content outside the managed block', () => {
    writeFileSync(
      path.join(memoryDir, 'INDEX.md'),
      [
        '# Memory index',
        '',
        'Hand-written intro that must be preserved.',
        '',
        '<!-- MNEMA: managed section, regenerated by `mnema memory consolidate` -->',
        '',
        '_(stale entries here will be replaced)_',
        '',
        '<!-- /MNEMA -->',
        '',
        'Footer paragraph also preserved.',
        '',
      ].join('\n'),
      'utf-8',
    );
    writeFileSync(path.join(memoryDir, 'context.md'), '# Project context\n', 'utf-8');

    new MemoryConsolidator(memoryDir).run();
    const result = readFileSync(path.join(memoryDir, 'INDEX.md'), 'utf-8');
    expect(result).toContain('Hand-written intro that must be preserved.');
    expect(result).toContain('Footer paragraph also preserved.');
    expect(result).toContain('[Project context](context.md)');
    expect(result).not.toContain('stale entries');
  });

  it('extracts title and metadata from frontmatter when present', () => {
    writeFileSync(
      path.join(memoryDir, 'decisions', '0001-use-zod.md'),
      [
        '---',
        'title: Use Zod for runtime validation',
        'status: accepted',
        'tags: [validation, runtime]',
        '---',
        '',
        '# Long heading should yield to frontmatter title',
        '',
      ].join('\n'),
      'utf-8',
    );

    const summary = new MemoryConsolidator(memoryDir).run();
    const decision = summary.decisions?.entries[0];
    expect(decision?.title).toBe('Use Zod for runtime validation');
    expect(decision?.status).toBe('accepted');
    expect(decision?.tags).toEqual(['validation', 'runtime']);

    const indexBody = readFileSync(path.join(memoryDir, 'decisions', 'INDEX.md'), 'utf-8');
    expect(indexBody).toContain('status: accepted');
    expect(indexBody).toContain('tags: validation, runtime');
  });

  it('is idempotent — second run produces byte-identical output', () => {
    writeFileSync(path.join(memoryDir, 'context.md'), '# Project context\n', 'utf-8');

    const consolidator = new MemoryConsolidator(memoryDir);
    consolidator.run();
    const first = readFileSync(path.join(memoryDir, 'INDEX.md'), 'utf-8');
    consolidator.run();
    const second = readFileSync(path.join(memoryDir, 'INDEX.md'), 'utf-8');

    expect(second).toBe(first);
  });

  it('emits the empty-state placeholder when the folder has no source files', () => {
    new MemoryConsolidator(memoryDir).run();
    const decisionsIndex = readFileSync(path.join(memoryDir, 'decisions', 'INDEX.md'), 'utf-8');
    expect(decisionsIndex).toContain('(no files yet)');
  });
});
