/**
 * The `mnema brief` wiring: what it declares, and what it prints.
 *
 * `mnema brief` — the decisions in force and the adopted patterns of the COMMITTED
 * record, as the markdown file an agent host reads on its own. It takes NO options at
 * all, which makes it the only read here with none, and every one it does not take was
 * decided rather than skipped: no `--actor` (the answer is the project's, not an
 * asker's), no `--check` (a pipe into `diff` answers that, and does not have to guess
 * where the operator's file is), no `--json` — the document IS the contract, and a
 * second serialization of the same answer would be a second thing to keep byte-stable
 * for no consumer, since what reads this file reads markdown.
 *
 * AND NO `--scope`, which is the one absence a reader of this list will look for now
 * that the document has a scope. It has ONE, and it is the point rather than a default
 * to override: the file is written to be committed, so what it carries is what a clone
 * gets. A flag would offer to put a private rule into a tracked file — the defect this
 * verb was corrected for — and the reader who wants the whole of what governs their
 * own work has the agent's opening context, which spans every tree.
 *
 * The whole output goes to stdout and nothing else. `mnema brief > AGENTS.md` is the
 * operator's choice; the help says so, because a verb whose point is a file is a
 * verb a reader will expect to write one.
 *
 * The DOCUMENT names the agent's doors (`read_record`, `skills`) and this HELP names
 * the command line's (`mnema show <id>`), which is not an inconsistency but the
 * division the product already draws: the file is read by an agent, and the help by
 * the person who typed the verb. Each is told the door it can actually open.
 */

import type { Command } from 'commander';
import { here } from './context.js';
import { writeLines } from './io.js';
import { reportRefusal } from './report.js';
import type { Wiring } from './verb.js';

/** Registers `mnema brief` on the program. */
export function registerBrief(program: Command, wiring: Wiring): void {
  const { io } = wiring;
  program
    .command('brief')
    .description('print what governs the work here as markdown, for an agent to read')
    .addHelpText(
      'after',
      [
        '',
        'It prints to stdout and writes nothing — where the file goes is your choice:',
        '  mnema brief > AGENTS.md          the record, as the file agent hosts read',
        '  mnema brief | diff - AGENTS.md   whether that copy still matches the record',
        '',
        'The output holds no clock, no session and no path, so the same record always',
        'prints the same bytes and a difference is a difference in the record.',
        'It carries this project’s COMMITTED record — what a clone gets. A decision or a',
        'pattern recorded with `--scope private`, or in your global tree, governs your own',
        'work and is not in this file, which is written to be committed.',
        'It carries the RULES and the NAMES: a decision by title and `ADR-<n>` label, a',
        'pattern by name. Neither body is in it — a decision’s argument and a pattern’s',
        'text are both `mnema show <id>` (the file itself names the agent’s doors).',
        'It carries no work list: a queue changes by the hour, and a copy of one in a',
        'file regenerated by hand would be wrong between two runs.',
      ].join('\n'),
    )
    .action(async () => {
      const { runBrief } = await import('../commands/brief.js');
      const { briefDocument } = await import('../presentation/brief.js');
      const result = runBrief(here());
      if (!result.ok) {
        reportRefusal(wiring, result);
        return;
      }
      writeLines(io, briefDocument(result.brief));
    });
}
